/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckRequest,
  DecisionResponse,
  Problem,
} from '../models/index';
import {
    CheckRequestFromJSON,
    CheckRequestToJSON,
    DecisionResponseFromJSON,
    DecisionResponseToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface RiskCheckRequest {
    xIdempotencyKey: string;
    checkRequest: CheckRequest;
    xTraceId?: string;
}

/**
 * 
 */
export class RiskScoringApi extends runtime.BaseAPI {

    /**
     * Assess Transaction Risk
     */
    async riskCheckRaw(requestParameters: RiskCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionResponse>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling riskCheck().'
            );
        }

        if (requestParameters['checkRequest'] == null) {
            throw new runtime.RequiredError(
                'checkRequest',
                'Required parameter "checkRequest" was null or undefined when calling riskCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/risk/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckRequestToJSON(requestParameters['checkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionResponseFromJSON(jsonValue));
    }

    /**
     * Assess Transaction Risk
     */
    async riskCheck(requestParameters: RiskCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionResponse> {
        const response = await this.riskCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
