/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountCheckRequest,
  DecisionResponse,
  KycCheckRequest,
  Problem,
} from '../models/index';
import {
    AccountCheckRequestFromJSON,
    AccountCheckRequestToJSON,
    DecisionResponseFromJSON,
    DecisionResponseToJSON,
    KycCheckRequestFromJSON,
    KycCheckRequestToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface AccountRiskCheckRequest {
    xIdempotencyKey: string;
    accountCheckRequest: AccountCheckRequest;
    xTraceId?: string;
}

export interface KycRiskCheckRequest {
    xIdempotencyKey: string;
    kycCheckRequest: KycCheckRequest;
    xTraceId?: string;
}

/**
 * 
 */
export class RoadmapPreviewApi extends runtime.BaseAPI {

    /**
     * > **Coming Soon**: This endpoint is currently in active development. Assess risk for account-level events such as signup, login, and profile changes. 
     * Synchronous fraud decision for account/session events
     */
    async accountRiskCheckRaw(requestParameters: AccountRiskCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionResponse>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling accountRiskCheck().'
            );
        }

        if (requestParameters['accountCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'accountCheckRequest',
                'Required parameter "accountCheckRequest" was null or undefined when calling accountRiskCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/risk/account/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccountCheckRequestToJSON(requestParameters['accountCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionResponseFromJSON(jsonValue));
    }

    /**
     * > **Coming Soon**: This endpoint is currently in active development. Assess risk for account-level events such as signup, login, and profile changes. 
     * Synchronous fraud decision for account/session events
     */
    async accountRiskCheck(requestParameters: AccountRiskCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionResponse> {
        const response = await this.accountRiskCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * > **Coming Soon**: This endpoint is currently in active development. Assess risk for identity verification and KYC workflows. 
     * Synchronous decision for KYC/identity verification
     */
    async kycRiskCheckRaw(requestParameters: KycRiskCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DecisionResponse>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling kycRiskCheck().'
            );
        }

        if (requestParameters['kycCheckRequest'] == null) {
            throw new runtime.RequiredError(
                'kycCheckRequest',
                'Required parameter "kycCheckRequest" was null or undefined when calling kycRiskCheck().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/risk/kyc/check`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KycCheckRequestToJSON(requestParameters['kycCheckRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DecisionResponseFromJSON(jsonValue));
    }

    /**
     * > **Coming Soon**: This endpoint is currently in active development. Assess risk for identity verification and KYC workflows. 
     * Synchronous decision for KYC/identity verification
     */
    async kycRiskCheck(requestParameters: KycRiskCheckRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DecisionResponse> {
        const response = await this.kycRiskCheckRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
