/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentEvent,
  Problem,
  SignalsRequest,
} from '../models/index';
import {
    PaymentEventFromJSON,
    PaymentEventToJSON,
    ProblemFromJSON,
    ProblemToJSON,
    SignalsRequestFromJSON,
    SignalsRequestToJSON,
} from '../models/index';

export interface IngestPaymentEventRequest {
    xIdempotencyKey: string;
    paymentEvent: PaymentEvent;
    xTraceId?: string;
}

export interface IngestSignalsRequest {
    xIdempotencyKey: string;
    signalsRequest: SignalsRequest;
    xTraceId?: string;
}

/**
 * 
 */
export class SignalIntelligenceApi extends runtime.BaseAPI {

    /**
     * Ingest Lifecycle Signals
     */
    async ingestPaymentEventRaw(requestParameters: IngestPaymentEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling ingestPaymentEvent().'
            );
        }

        if (requestParameters['paymentEvent'] == null) {
            throw new runtime.RequiredError(
                'paymentEvent',
                'Required parameter "paymentEvent" was null or undefined when calling ingestPaymentEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/events`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentEventToJSON(requestParameters['paymentEvent']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ingest Lifecycle Signals
     */
    async ingestPaymentEvent(requestParameters: IngestPaymentEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestPaymentEventRaw(requestParameters, initOverrides);
    }

    /**
     * Submit Behavioral Intelligence
     */
    async ingestSignalsRaw(requestParameters: IngestSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling ingestSignals().'
            );
        }

        if (requestParameters['signalsRequest'] == null) {
            throw new runtime.RequiredError(
                'signalsRequest',
                'Required parameter "signalsRequest" was null or undefined when calling ingestSignals().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/signals`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignalsRequestToJSON(requestParameters['signalsRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit Behavioral Intelligence
     */
    async ingestSignals(requestParameters: IngestSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestSignalsRaw(requestParameters, initOverrides);
    }

}
