/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentEvent,
  Problem,
  SignalsRequest,
} from '../models/index';
import {
    PaymentEventFromJSON,
    PaymentEventToJSON,
    ProblemFromJSON,
    ProblemToJSON,
    SignalsRequestFromJSON,
    SignalsRequestToJSON,
} from '../models/index';

export interface IngestPaymentEventRequest {
    xIdempotencyKey: string;
    paymentEvent: PaymentEvent;
    xTraceId?: string;
}

export interface IngestSignalsRequest {
    xIdempotencyKey: string;
    signalsRequest: SignalsRequest;
    xTraceId?: string;
}

/**
 * 
 */
export class SignalIntelligenceApi extends runtime.BaseAPI {

    /**
     * Ingest Lifecycle Signals
     */
    async ingestPaymentEventRaw(requestParameters: IngestPaymentEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling ingestPaymentEvent().'
            );
        }

        if (requestParameters['paymentEvent'] == null) {
            throw new runtime.RequiredError(
                'paymentEvent',
                'Required parameter "paymentEvent" was null or undefined when calling ingestPaymentEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/events`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentEventToJSON(requestParameters['paymentEvent']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ingest Lifecycle Signals
     */
    async ingestPaymentEvent(requestParameters: IngestPaymentEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestPaymentEventRaw(requestParameters, initOverrides);
    }

    /**
     * Submit Behavioral Intelligence
     */
    async ingestSignalsRaw(requestParameters: IngestSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xIdempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'xIdempotencyKey',
                'Required parameter "xIdempotencyKey" was null or undefined when calling ingestSignals().'
            );
        }

        if (requestParameters['signalsRequest'] == null) {
            throw new runtime.RequiredError(
                'signalsRequest',
                'Required parameter "signalsRequest" was null or undefined when calling ingestSignals().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xTraceId'] != null) {
            headerParameters['x-trace-id'] = String(requestParameters['xTraceId']);
        }

        if (requestParameters['xIdempotencyKey'] != null) {
            headerParameters['x-idempotency-key'] = String(requestParameters['xIdempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oAuth2", ["payrisk.write"]);
        }


        let urlPath = `/v1/signals`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignalsRequestToJSON(requestParameters['signalsRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit Behavioral Intelligence
     */
    async ingestSignals(requestParameters: IngestSignalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.ingestSignalsRaw(requestParameters, initOverrides);
    }

}
