/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { Interaction } from './Interaction';
import {
    InteractionFromJSON,
    InteractionFromJSONTyped,
    InteractionToJSON,
    InteractionToJSONTyped,
} from './Interaction';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';

/**
 * 
 * @export
 * @interface AccountCheckRequest
 */
export interface AccountCheckRequest {
    /**
     * The specific subtype of the account event (e.g., 'signup', 'login').
     * @type {string}
     * @memberof AccountCheckRequest
     */
    eventSubtype: AccountCheckRequestEventSubtypeEnum;
    /**
     * 
     * @type {EntityIds}
     * @memberof AccountCheckRequest
     */
    entities?: EntityIds;
    /**
     * 
     * @type {Account}
     * @memberof AccountCheckRequest
     */
    account?: Account;
    /**
     * 
     * @type {Interaction}
     * @memberof AccountCheckRequest
     */
    interaction?: Interaction;
}

/**
* @export
* @enum {string}
*/
export enum AccountCheckRequestEventSubtypeEnum {
    Signup = 'signup',
    Login = 'login',
    PasswordReset = 'password_reset',
    MfaReset = 'mfa_reset',
    SettingChange = 'setting_change'
}


/**
 * Check if a given object implements the AccountCheckRequest interface.
 */
export function instanceOfAccountCheckRequest(value: object): value is AccountCheckRequest {
    if (!('eventSubtype' in value) || value['eventSubtype'] === undefined) return false;
    return true;
}

export function AccountCheckRequestFromJSON(json: any): AccountCheckRequest {
    return AccountCheckRequestFromJSONTyped(json, false);
}

export function AccountCheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSubtype': json['eventSubtype'],
        'entities': json['entities'] == null ? undefined : EntityIdsFromJSON(json['entities']),
        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
        'interaction': json['interaction'] == null ? undefined : InteractionFromJSON(json['interaction']),
    };
}

export function AccountCheckRequestToJSON(json: any): AccountCheckRequest {
    return AccountCheckRequestToJSONTyped(json, false);
}

export function AccountCheckRequestToJSONTyped(value?: AccountCheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSubtype': value['eventSubtype'],
        'entities': EntityIdsToJSON(value['entities']),
        'account': AccountToJSON(value['account']),
        'interaction': InteractionToJSON(value['interaction']),
    };
}
