/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { Interaction } from './Interaction';
import {
    InteractionFromJSON,
    InteractionFromJSONTyped,
    InteractionToJSON,
    InteractionToJSONTyped,
} from './Interaction';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';

/**
 * 
 * @export
 * @interface AccountCheckRequest
 */
export interface AccountCheckRequest {
    /**
     * The specific subtype of the account event (e.g., 'signup', 'login').
     * @type {string}
     * @memberof AccountCheckRequest
     */
    eventSubtype: AccountCheckRequestEventSubtypeEnum;
    /**
     * 
     * @type {EntityIds}
     * @memberof AccountCheckRequest
     */
    entities?: EntityIds;
    /**
     * 
     * @type {Account}
     * @memberof AccountCheckRequest
     */
    account?: Account;
    /**
     * 
     * @type {Interaction}
     * @memberof AccountCheckRequest
     */
    interaction?: Interaction;
}

/**
* @export
* @enum {string}
*/
export enum AccountCheckRequestEventSubtypeEnum {
    Signup = 'signup',
    Login = 'login',
    PasswordReset = 'password_reset',
    MfaReset = 'mfa_reset',
    SettingChange = 'setting_change'
}


/**
 * Check if a given object implements the AccountCheckRequest interface.
 */
export function instanceOfAccountCheckRequest(value: object): value is AccountCheckRequest {
    if (!('eventSubtype' in value) || value['eventSubtype'] === undefined) return false;
    return true;
}

export function AccountCheckRequestFromJSON(json: any): AccountCheckRequest {
    return AccountCheckRequestFromJSONTyped(json, false);
}

export function AccountCheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountCheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'eventSubtype': json['eventSubtype'],
        'entities': json['entities'] == null ? undefined : EntityIdsFromJSON(json['entities']),
        'account': json['account'] == null ? undefined : AccountFromJSON(json['account']),
        'interaction': json['interaction'] == null ? undefined : InteractionFromJSON(json['interaction']),
    };
}

export function AccountCheckRequestToJSON(json: any): AccountCheckRequest {
    return AccountCheckRequestToJSONTyped(json, false);
}

export function AccountCheckRequestToJSONTyped(value?: AccountCheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventSubtype': value['eventSubtype'],
        'entities': EntityIdsToJSON(value['entities']),
        'account': AccountToJSON(value['account']),
        'interaction': InteractionToJSON(value['interaction']),
    };
}

