/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.21
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentProvider } from './AgentProvider';
import {
    AgentProviderFromJSON,
    AgentProviderFromJSONTyped,
    AgentProviderToJSON,
    AgentProviderToJSONTyped,
} from './AgentProvider';

/**
 * Proof of delegation for an autonomous shopping agent (UCP/MCP compatible).  Allows PayRisk to verify the "Who" and "Trust" behind a machine-driven transaction.
 * 
 * @export
 * @interface AgentManifest
 */
export interface AgentManifest {
    /**
     * 
     * @type {AgentProvider}
     * @memberof AgentManifest
     */
    provider: AgentProvider;
    /**
     * Specific model version of the agent.
     * @type {string}
     * @memberof AgentManifest
     */
    model: string;
    /**
     * Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Supports "ecid_" slugs (Legacy) or "cus_" hex (Preferred).
     * 
     * @type {string}
     * @memberof AgentManifest
     */
    principalId: string;
    /**
     * Platform-provided reputation score for the agent.
     * @type {number}
     * @memberof AgentManifest
     */
    trustTier: number;
    /**
     * Authorized scope of authority for the agent.
     * @type {Array<string>}
     * @memberof AgentManifest
     */
    capabilities?: Array<string>;
}



/**
 * Check if a given object implements the AgentManifest interface.
 */
export function instanceOfAgentManifest(value: object): value is AgentManifest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('principalId' in value) || value['principalId'] === undefined) return false;
    if (!('trustTier' in value) || value['trustTier'] === undefined) return false;
    return true;
}

export function AgentManifestFromJSON(json: any): AgentManifest {
    return AgentManifestFromJSONTyped(json, false);
}

export function AgentManifestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentManifest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': AgentProviderFromJSON(json['provider']),
        'model': json['model'],
        'principalId': json['principalId'],
        'trustTier': json['trustTier'],
        'capabilities': json['capabilities'] == null ? undefined : json['capabilities'],
    };
}

export function AgentManifestToJSON(json: any): AgentManifest {
    return AgentManifestToJSONTyped(json, false);
}

export function AgentManifestToJSONTyped(value?: AgentManifest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': AgentProviderToJSON(value['provider']),
        'model': value['model'],
        'principalId': value['principalId'],
        'trustTier': value['trustTier'],
        'capabilities': value['capabilities'],
    };
}

