/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AVS response codes:
 * Y: Address and 5-digit ZIP match
 * N: Address and 5-digit ZIP do not match
 * A: Address matches, ZIP does not
 * Z: ZIP matches, address does not
 * U: Address unavailable
 * R: System unavailable
 * S: Not supported
 * G: Global non-AVS
 * B: International AVS
 * C: Street address and postal code not verified due to incompatible formats
 * D: Street address and postal code not verified due to incompatible formats
 * M: Street address and postal code match
 * P: Street address not verified. Postal code matches.
 * X: Street address and 9-digit ZIP match
 * W: Street address not verified. 9-digit ZIP matches.
 * 
 * @export
 * @enum {string}
 */
export enum AvsResultEnum {
    Y = 'Y',
    N = 'N',
    A = 'A',
    Z = 'Z',
    U = 'U',
    R = 'R',
    S = 'S',
    G = 'G',
    B = 'B',
    C = 'C',
    D = 'D',
    M = 'M',
    P = 'P',
    X = 'X',
    W = 'W'
}


export function instanceOfAvsResultEnum(value: any): boolean {
    for (const key in AvsResultEnum) {
        if (Object.prototype.hasOwnProperty.call(AvsResultEnum, key)) {
            if (AvsResultEnum[key as keyof typeof AvsResultEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AvsResultEnumFromJSON(json: any): AvsResultEnum {
    return AvsResultEnumFromJSONTyped(json, false);
}

export function AvsResultEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvsResultEnum {
    return json as AvsResultEnum;
}

export function AvsResultEnumToJSON(value?: AvsResultEnum | null): any {
    return value as any;
}

export function AvsResultEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AvsResultEnum {
    return value as AvsResultEnum;
}

