/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * AVS response codes:
 * Y: Address and 5-digit ZIP match
 * N: Address and 5-digit ZIP do not match
 * A: Address matches, ZIP does not
 * Z: ZIP matches, address does not
 * U: Address unavailable
 * R: System unavailable
 * S: Not supported
 * G: Global non-AVS
 * B: International AVS
 * C: Street address and postal code not verified due to incompatible formats
 * D: Street address and postal code not verified due to incompatible formats
 * M: Street address and postal code match
 * P: Street address not verified. Postal code matches.
 * X: Street address and 9-digit ZIP match
 * W: Street address not verified. 9-digit ZIP matches.
 * 
 * @export
 * @enum {string}
 */
export enum AvsResultEnum {
    Y = 'Y',
    N = 'N',
    A = 'A',
    Z = 'Z',
    U = 'U',
    R = 'R',
    S = 'S',
    G = 'G',
    B = 'B',
    C = 'C',
    D = 'D',
    M = 'M',
    P = 'P',
    X = 'X',
    W = 'W'
}


export function instanceOfAvsResultEnum(value: any): boolean {
    for (const key in AvsResultEnum) {
        if (Object.prototype.hasOwnProperty.call(AvsResultEnum, key)) {
            if (AvsResultEnum[key as keyof typeof AvsResultEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AvsResultEnumFromJSON(json: any): AvsResultEnum {
    return AvsResultEnumFromJSONTyped(json, false);
}

export function AvsResultEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvsResultEnum {
    return json as AvsResultEnum;
}

export function AvsResultEnumToJSON(value?: AvsResultEnum | null): any {
    return value as any;
}

export function AvsResultEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): AvsResultEnum {
    return value as AvsResultEnum;
}

