/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankTransfer
 */
export interface BankTransfer {
    /**
     * Fixed to `bank_transfer` for this schema.
     * @type {string}
     * @memberof BankTransfer
     */
    type: BankTransferTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum BankTransferTypeEnum {
    BankTransfer = 'bank_transfer'
}


/**
 * Check if a given object implements the BankTransfer interface.
 */
export function instanceOfBankTransfer(value: object): value is BankTransfer {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function BankTransferFromJSON(json: any): BankTransfer {
    return BankTransferFromJSONTyped(json, false);
}

export function BankTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransfer {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function BankTransferToJSON(json: any): BankTransfer {
    return BankTransferToJSONTyped(json, false);
}

export function BankTransferToJSONTyped(value?: BankTransfer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}
