/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Traditional bank transfer (e.g., ACH, SEPA Credit Transfer); keep payload minimal.
 * @export
 * @interface BankTransfer
 */
export interface BankTransfer {
    /**
     * Fixed to `bank_transfer` for this schema.
     * @type {string}
     * @memberof BankTransfer
     */
    type: BankTransferTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum BankTransferTypeEnum {
    BankTransfer = 'bank_transfer'
}


/**
 * Check if a given object implements the BankTransfer interface.
 */
export function instanceOfBankTransfer(value: object): value is BankTransfer {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function BankTransferFromJSON(json: any): BankTransfer {
    return BankTransferFromJSONTyped(json, false);
}

export function BankTransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransfer {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function BankTransferToJSON(json: any): BankTransfer {
    return BankTransferToJSONTyped(json, false);
}

export function BankTransferToJSONTyped(value?: BankTransfer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

