/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentCardTypeEnum } from './PaymentCardTypeEnum';
import {
    PaymentCardTypeEnumFromJSON,
    PaymentCardTypeEnumFromJSONTyped,
    PaymentCardTypeEnumToJSON,
    PaymentCardTypeEnumToJSONTyped,
} from './PaymentCardTypeEnum';
import type { AvsResultEnum } from './AvsResultEnum';
import {
    AvsResultEnumFromJSON,
    AvsResultEnumFromJSONTyped,
    AvsResultEnumToJSON,
    AvsResultEnumToJSONTyped,
} from './AvsResultEnum';
import type { CardNetworkEnum } from './CardNetworkEnum';
import {
    CardNetworkEnumFromJSON,
    CardNetworkEnumFromJSONTyped,
    CardNetworkEnumToJSON,
    CardNetworkEnumToJSONTyped,
} from './CardNetworkEnum';
import type { ThreeDSData } from './ThreeDSData';
import {
    ThreeDSDataFromJSON,
    ThreeDSDataFromJSONTyped,
    ThreeDSDataToJSON,
    ThreeDSDataToJSONTyped,
} from './ThreeDSData';
import type { ScaMethodEnum } from './ScaMethodEnum';
import {
    ScaMethodEnumFromJSON,
    ScaMethodEnumFromJSONTyped,
    ScaMethodEnumToJSON,
    ScaMethodEnumToJSONTyped,
} from './ScaMethodEnum';
import type { CvvResultEnum } from './CvvResultEnum';
import {
    CvvResultEnumFromJSON,
    CvvResultEnumFromJSONTyped,
    CvvResultEnumToJSON,
    CvvResultEnumToJSONTyped,
} from './CvvResultEnum';

/**
 * Card attributes (network, BIN/IIN, issuer country, AVS/CVV, SCA, optional 3DS).
 * @export
 * @interface Card
 */
export interface Card {
    /**
     * Fixed to `card` for this schema.
     * @type {string}
     * @memberof Card
     */
    type: CardTypeEnum;
    /**
     * 
     * @type {CardNetworkEnum}
     * @memberof Card
     */
    cardNetwork?: CardNetworkEnum;
    /**
     * 
     * @type {PaymentCardTypeEnum}
     * @memberof Card
     */
    cardType?: PaymentCardTypeEnum;
    /**
     * Bank Identification Number (IIN). First 6-8 digits of the PAN; do not send full PAN.
     * @type {string}
     * @memberof Card
     */
    bin?: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof Card
     */
    issuerCountry?: string;
    /**
     * 
     * @type {AvsResultEnum}
     * @memberof Card
     */
    avsResult?: AvsResultEnum;
    /**
     * 
     * @type {CvvResultEnum}
     * @memberof Card
     */
    cvvResult?: CvvResultEnum;
    /**
     * 
     * @type {ScaMethodEnum}
     * @memberof Card
     */
    scaMethod?: ScaMethodEnum;
    /**
     * 
     * @type {ThreeDSData}
     * @memberof Card
     */
    threeDS?: ThreeDSData;
}

/**
* @export
* @enum {string}
*/
export enum CardTypeEnum {
    Card = 'card'
}


/**
 * Check if a given object implements the Card interface.
 */
export function instanceOfCard(value: object): value is Card {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CardFromJSON(json: any): Card {
    return CardFromJSONTyped(json, false);
}

export function CardFromJSONTyped(json: any, ignoreDiscriminator: boolean): Card {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'cardNetwork': json['cardNetwork'] == null ? undefined : CardNetworkEnumFromJSON(json['cardNetwork']),
        'cardType': json['cardType'] == null ? undefined : PaymentCardTypeEnumFromJSON(json['cardType']),
        'bin': json['bin'] == null ? undefined : json['bin'],
        'issuerCountry': json['issuerCountry'] == null ? undefined : json['issuerCountry'],
        'avsResult': json['avsResult'] == null ? undefined : AvsResultEnumFromJSON(json['avsResult']),
        'cvvResult': json['cvvResult'] == null ? undefined : CvvResultEnumFromJSON(json['cvvResult']),
        'scaMethod': json['scaMethod'] == null ? undefined : ScaMethodEnumFromJSON(json['scaMethod']),
        'threeDS': json['threeDS'] == null ? undefined : ThreeDSDataFromJSON(json['threeDS']),
    };
}

export function CardToJSON(json: any): Card {
    return CardToJSONTyped(json, false);
}

export function CardToJSONTyped(value?: Card | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'cardNetwork': CardNetworkEnumToJSON(value['cardNetwork']),
        'cardType': PaymentCardTypeEnumToJSON(value['cardType']),
        'bin': value['bin'],
        'issuerCountry': value['issuerCountry'],
        'avsResult': AvsResultEnumToJSON(value['avsResult']),
        'cvvResult': CvvResultEnumToJSON(value['cvvResult']),
        'scaMethod': ScaMethodEnumToJSON(value['scaMethod']),
        'threeDS': ThreeDSDataToJSON(value['threeDS']),
    };
}

