/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of card network.
 * @export
 * @enum {string}
 */
export enum CardNetworkEnum {
    Visa = 'visa',
    Mastercard = 'mastercard',
    Amex = 'amex',
    Discover = 'discover',
    Jcb = 'jcb',
    Unionpay = 'unionpay',
    Other = 'other'
}


export function instanceOfCardNetworkEnum(value: any): boolean {
    for (const key in CardNetworkEnum) {
        if (Object.prototype.hasOwnProperty.call(CardNetworkEnum, key)) {
            if (CardNetworkEnum[key as keyof typeof CardNetworkEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CardNetworkEnumFromJSON(json: any): CardNetworkEnum {
    return CardNetworkEnumFromJSONTyped(json, false);
}

export function CardNetworkEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardNetworkEnum {
    return json as CardNetworkEnum;
}

export function CardNetworkEnumToJSON(value?: CardNetworkEnum | null): any {
    return value as any;
}

export function CardNetworkEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CardNetworkEnum {
    return value as CardNetworkEnum;
}

