/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of card network.
 * @export
 * @enum {string}
 */
export enum CardNetworkEnum {
    Visa = 'visa',
    Mastercard = 'mastercard',
    Amex = 'amex',
    Discover = 'discover',
    Jcb = 'jcb',
    Unionpay = 'unionpay',
    Other = 'other'
}


export function instanceOfCardNetworkEnum(value: any): boolean {
    for (const key in CardNetworkEnum) {
        if (Object.prototype.hasOwnProperty.call(CardNetworkEnum, key)) {
            if (CardNetworkEnum[key as keyof typeof CardNetworkEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CardNetworkEnumFromJSON(json: any): CardNetworkEnum {
    return CardNetworkEnumFromJSONTyped(json, false);
}

export function CardNetworkEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardNetworkEnum {
    return json as CardNetworkEnum;
}

export function CardNetworkEnumToJSON(value?: CardNetworkEnum | null): any {
    return value as any;
}

export function CardNetworkEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CardNetworkEnum {
    return value as CardNetworkEnum;
}

