/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskLevelEnum } from './RiskLevelEnum';
import {
    RiskLevelEnumFromJSON,
    RiskLevelEnumFromJSONTyped,
    RiskLevelEnumToJSON,
    RiskLevelEnumToJSONTyped,
} from './RiskLevelEnum';

/**
 * Risk analysis for a specific business category.
 * @export
 * @interface CategorySignal
 */
export interface CategorySignal {
    /**
     * 
     * @type {RiskLevelEnum}
     * @memberof CategorySignal
     */
    level: RiskLevelEnum;
    /**
     * Category-specific risk score (0.00 - 1.00).
     * @type {number}
     * @memberof CategorySignal
     */
    score?: number;
    /**
     * Specific reason codes for this category.
     * @type {Array<string>}
     * @memberof CategorySignal
     */
    reasons?: Array<string>;
    /**
     * Derived evidence and enrichment data for this category.
     * @type {object}
     * @memberof CategorySignal
     */
    metadata?: object;
}



/**
 * Check if a given object implements the CategorySignal interface.
 */
export function instanceOfCategorySignal(value: object): value is CategorySignal {
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function CategorySignalFromJSON(json: any): CategorySignal {
    return CategorySignalFromJSONTyped(json, false);
}

export function CategorySignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySignal {
    if (json == null) {
        return json;
    }
    return {
        
        'level': RiskLevelEnumFromJSON(json['level']),
        'score': json['score'] == null ? undefined : json['score'],
        'reasons': json['reasons'] == null ? undefined : json['reasons'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CategorySignalToJSON(json: any): CategorySignal {
    return CategorySignalToJSONTyped(json, false);
}

export function CategorySignalToJSONTyped(value?: CategorySignal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': RiskLevelEnumToJSON(value['level']),
        'score': value['score'],
        'reasons': value['reasons'],
        'metadata': value['metadata'],
    };
}

