/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskLevelEnum } from './RiskLevelEnum';
import {
    RiskLevelEnumFromJSON,
    RiskLevelEnumFromJSONTyped,
    RiskLevelEnumToJSON,
    RiskLevelEnumToJSONTyped,
} from './RiskLevelEnum';

/**
 * Risk analysis for a specific business category.
 * @export
 * @interface CategorySignal
 */
export interface CategorySignal {
    /**
     * 
     * @type {RiskLevelEnum}
     * @memberof CategorySignal
     */
    level: RiskLevelEnum;
    /**
     * Category-specific risk score (0.00 - 1.00).
     * @type {number}
     * @memberof CategorySignal
     */
    score?: number;
    /**
     * Specific reason codes for this category.
     * @type {Array<string>}
     * @memberof CategorySignal
     */
    reasons?: Array<string>;
    /**
     * Derived evidence and enrichment data for this category.
     * @type {object}
     * @memberof CategorySignal
     */
    metadata?: object;
}



/**
 * Check if a given object implements the CategorySignal interface.
 */
export function instanceOfCategorySignal(value: object): value is CategorySignal {
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function CategorySignalFromJSON(json: any): CategorySignal {
    return CategorySignalFromJSONTyped(json, false);
}

export function CategorySignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySignal {
    if (json == null) {
        return json;
    }
    return {
        
        'level': RiskLevelEnumFromJSON(json['level']),
        'score': json['score'] == null ? undefined : json['score'],
        'reasons': json['reasons'] == null ? undefined : json['reasons'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CategorySignalToJSON(json: any): CategorySignal {
    return CategorySignalToJSONTyped(json, false);
}

export function CategorySignalToJSONTyped(value?: CategorySignal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': RiskLevelEnumToJSON(value['level']),
        'score': value['score'],
        'reasons': value['reasons'],
        'metadata': value['metadata'],
    };
}

