/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * pos: 'Point of Sale', ecom: 'E-commerce', in_app: 'In-App Purchase', ivr: 'Interactive Voice Response'.
 * 
 * @export
 * @enum {string}
 */
export enum ChannelEnum {
    Pos = 'pos',
    Ecom = 'ecom',
    InApp = 'in_app',
    Ivr = 'ivr'
}


export function instanceOfChannelEnum(value: any): boolean {
    for (const key in ChannelEnum) {
        if (Object.prototype.hasOwnProperty.call(ChannelEnum, key)) {
            if (ChannelEnum[key as keyof typeof ChannelEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChannelEnumFromJSON(json: any): ChannelEnum {
    return ChannelEnumFromJSONTyped(json, false);
}

export function ChannelEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelEnum {
    return json as ChannelEnum;
}

export function ChannelEnumToJSON(value?: ChannelEnum | null): any {
    return value as any;
}

export function ChannelEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ChannelEnum {
    return value as ChannelEnum;
}
