/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Purchase } from './Purchase';
import {
    PurchaseFromJSON,
    PurchaseFromJSONTyped,
    PurchaseToJSON,
    PurchaseToJSONTyped,
} from './Purchase';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';
import type { Identity } from './Identity';
import {
    IdentityFromJSON,
    IdentityFromJSONTyped,
    IdentityToJSON,
    IdentityToJSONTyped,
} from './Identity';

/**
 * Request for synchronous purchase risk check.
 * @export
 * @interface CheckRequest
 */
export interface CheckRequest {
    /**
     * (optional) event being checked, this may expand later beyond 'purchase'.
     * @type {string}
     * @memberof CheckRequest
     */
    eventType?: CheckRequestEventTypeEnum;
    /**
     * Server-minted unique payment identifier.
     * @type {string}
     * @memberof CheckRequest
     */
    paymentIntentId?: string;
    /**
     * 
     * @type {EntityIds}
     * @memberof CheckRequest
     */
    entities: EntityIds;
    /**
     * 
     * @type {Purchase}
     * @memberof CheckRequest
     */
    purchase: Purchase;
    /**
     * 
     * @type {Identity}
     * @memberof CheckRequest
     */
    identity?: Identity;
}

/**
* @export
* @enum {string}
*/
export enum CheckRequestEventTypeEnum {
    Purchase = 'purchase'
}


/**
 * Check if a given object implements the CheckRequest interface.
 */
export function instanceOfCheckRequest(value: object): value is CheckRequest {
    if (!('entities' in value) || value['entities'] === undefined) return false;
    if (!('purchase' in value) || value['purchase'] === undefined) return false;
    return true;
}

export function CheckRequestFromJSON(json: any): CheckRequest {
    return CheckRequestFromJSONTyped(json, false);
}

export function CheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'eventType': json['eventType'] == null ? undefined : json['eventType'],
        'paymentIntentId': json['paymentIntentId'] == null ? undefined : json['paymentIntentId'],
        'entities': EntityIdsFromJSON(json['entities']),
        'purchase': PurchaseFromJSON(json['purchase']),
        'identity': json['identity'] == null ? undefined : IdentityFromJSON(json['identity']),
    };
}

export function CheckRequestToJSON(json: any): CheckRequest {
    return CheckRequestToJSONTyped(json, false);
}

export function CheckRequestToJSONTyped(value?: CheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventType': value['eventType'],
        'paymentIntentId': value['paymentIntentId'],
        'entities': EntityIdsToJSON(value['entities']),
        'purchase': PurchaseToJSON(value['purchase']),
        'identity': IdentityToJSON(value['identity']),
    };
}
