/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The confidence level of the risk assessment.
 * @export
 * @enum {string}
 */
export enum ConfidenceEnum {
    Low = 'low',
    Medium = 'medium',
    High = 'high'
}


export function instanceOfConfidenceEnum(value: any): boolean {
    for (const key in ConfidenceEnum) {
        if (Object.prototype.hasOwnProperty.call(ConfidenceEnum, key)) {
            if (ConfidenceEnum[key as keyof typeof ConfidenceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConfidenceEnumFromJSON(json: any): ConfidenceEnum {
    return ConfidenceEnumFromJSONTyped(json, false);
}

export function ConfidenceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfidenceEnum {
    return json as ConfidenceEnum;
}

export function ConfidenceEnumToJSON(value?: ConfidenceEnum | null): any {
    return value as any;
}

export function ConfidenceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ConfidenceEnum {
    return value as ConfidenceEnum;
}

