/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The confidence level of the risk assessment.
 * @export
 * @enum {string}
 */
export enum ConfidenceEnum {
    Low = 'low',
    Medium = 'medium',
    High = 'high'
}


export function instanceOfConfidenceEnum(value: any): boolean {
    for (const key in ConfidenceEnum) {
        if (Object.prototype.hasOwnProperty.call(ConfidenceEnum, key)) {
            if (ConfidenceEnum[key as keyof typeof ConfidenceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConfidenceEnumFromJSON(json: any): ConfidenceEnum {
    return ConfidenceEnumFromJSONTyped(json, false);
}

export function ConfidenceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfidenceEnum {
    return json as ConfidenceEnum;
}

export function ConfidenceEnumToJSON(value?: ConfidenceEnum | null): any {
    return value as any;
}

export function ConfidenceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ConfidenceEnum {
    return value as ConfidenceEnum;
}

