/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * M: CVV match
 * N: CVV no match
 * P: Not processed
 * S: Should have been present
 * U: Unavailable
 * 
 * @export
 * @enum {string}
 */
export enum CvvResultEnum {
    M = 'M',
    N = 'N',
    P = 'P',
    S = 'S',
    U = 'U'
}


export function instanceOfCvvResultEnum(value: any): boolean {
    for (const key in CvvResultEnum) {
        if (Object.prototype.hasOwnProperty.call(CvvResultEnum, key)) {
            if (CvvResultEnum[key as keyof typeof CvvResultEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CvvResultEnumFromJSON(json: any): CvvResultEnum {
    return CvvResultEnumFromJSONTyped(json, false);
}

export function CvvResultEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CvvResultEnum {
    return json as CvvResultEnum;
}

export function CvvResultEnumToJSON(value?: CvvResultEnum | null): any {
    return value as any;
}

export function CvvResultEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CvvResultEnum {
    return value as CvvResultEnum;
}

