/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DecisionResolutionRequestAnalyst } from './DecisionResolutionRequestAnalyst';
import {
    DecisionResolutionRequestAnalystFromJSON,
    DecisionResolutionRequestAnalystFromJSONTyped,
    DecisionResolutionRequestAnalystToJSON,
    DecisionResolutionRequestAnalystToJSONTyped,
} from './DecisionResolutionRequestAnalyst';

/**
 * 
 * @export
 * @interface DecisionResolutionRequest
 */
export interface DecisionResolutionRequest {
    /**
     * The business entity type being resolved.
     * @type {string}
     * @memberof DecisionResolutionRequest
     */
    targetType: DecisionResolutionRequestTargetTypeEnum;
    /**
     * The unique identifier of the target entity under review (e.g. pi_*).
     * @type {string}
     * @memberof DecisionResolutionRequest
     */
    targetId: string;
    /**
     * The resolution action to apply to the target.
     * @type {string}
     * @memberof DecisionResolutionRequest
     */
    decision: DecisionResolutionRequestDecisionEnum;
    /**
     * 
     * @type {DecisionResolutionRequestAnalyst}
     * @memberof DecisionResolutionRequest
     */
    analyst: DecisionResolutionRequestAnalyst;
    /**
     * The ML-feedback ground-truth reason classification.
     * @type {string}
     * @memberof DecisionResolutionRequest
     */
    resolutionReason: DecisionResolutionRequestResolutionReasonEnum;
    /**
     * Additional operational notes or reasoning for this resolution.
     * @type {string}
     * @memberof DecisionResolutionRequest
     */
    notes?: string;
}

/**
* @export
* @enum {string}
*/
export enum DecisionResolutionRequestTargetTypeEnum {
    PaymentIntent = 'payment_intent',
    AccountEvent = 'account_event',
    AgentDelegation = 'agent_delegation'
}
/**
* @export
* @enum {string}
*/
export enum DecisionResolutionRequestDecisionEnum {
    Approve = 'approve',
    Block = 'block',
    Challenge = 'challenge',
    Escalate = 'escalate'
}
/**
* @export
* @enum {string}
*/
export enum DecisionResolutionRequestResolutionReasonEnum {
    LegitHuman = 'legit_human',
    LegitAgentAuthorized = 'legit_agent_authorized',
    UnauthorizedAgent = 'unauthorized_agent',
    CardTesting = 'card_testing',
    AccountTakeover = 'account_takeover',
    FriendlyFraud = 'friendly_fraud'
}


/**
 * Check if a given object implements the DecisionResolutionRequest interface.
 */
export function instanceOfDecisionResolutionRequest(value: object): value is DecisionResolutionRequest {
    if (!('targetType' in value) || value['targetType'] === undefined) return false;
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('analyst' in value) || value['analyst'] === undefined) return false;
    if (!('resolutionReason' in value) || value['resolutionReason'] === undefined) return false;
    return true;
}

export function DecisionResolutionRequestFromJSON(json: any): DecisionResolutionRequest {
    return DecisionResolutionRequestFromJSONTyped(json, false);
}

export function DecisionResolutionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionResolutionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetType': json['targetType'],
        'targetId': json['targetId'],
        'decision': json['decision'],
        'analyst': DecisionResolutionRequestAnalystFromJSON(json['analyst']),
        'resolutionReason': json['resolutionReason'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function DecisionResolutionRequestToJSON(json: any): DecisionResolutionRequest {
    return DecisionResolutionRequestToJSONTyped(json, false);
}

export function DecisionResolutionRequestToJSONTyped(value?: DecisionResolutionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'targetType': value['targetType'],
        'targetId': value['targetId'],
        'decision': value['decision'],
        'analyst': DecisionResolutionRequestAnalystToJSON(value['analyst']),
        'resolutionReason': value['resolutionReason'],
        'notes': value['notes'],
    };
}

