/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.3.2
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DecisionResponsePolicy } from './DecisionResponsePolicy';
import {
    DecisionResponsePolicyFromJSON,
    DecisionResponsePolicyFromJSONTyped,
    DecisionResponsePolicyToJSON,
    DecisionResponsePolicyToJSONTyped,
} from './DecisionResponsePolicy';
import type { ReasonDetail } from './ReasonDetail';
import {
    ReasonDetailFromJSON,
    ReasonDetailFromJSONTyped,
    ReasonDetailToJSON,
    ReasonDetailToJSONTyped,
} from './ReasonDetail';
import type { RiskBreakdown } from './RiskBreakdown';
import {
    RiskBreakdownFromJSON,
    RiskBreakdownFromJSONTyped,
    RiskBreakdownToJSON,
    RiskBreakdownToJSONTyped,
} from './RiskBreakdown';

/**
 * The synchronous risk decision for a purchase.
 * @export
 * @interface DecisionResponse
 */
export interface DecisionResponse {
    /**
     * Alogram's unique, authoritative evaluation and transaction identifier. Prefixed with 'pi_' for purchases.
     * @type {string}
     * @memberof DecisionResponse
     */
    id: string;
    /**
     * The authoritative, absolute policy command for this transaction. Downstream systems must bind their operational behavior (approve/decline/review) directly to this field.
     * @type {string}
     * @memberof DecisionResponse
     */
    decision: DecisionResponseDecisionEnum;
    /**
     * RFC 3339 timestamp with timezone.
     * @type {string}
     * @memberof DecisionResponse
     */
    decisionAt: string;
    /**
     * The authoritative, policy-adjusted blended risk score (0.0 - 1.0) derived from expert fusion.
     * @type {number}
     * @memberof DecisionResponse
     */
    riskScore: number;
    /**
     * Structured reason details for the decision.
     * @type {Array<ReasonDetail>}
     * @memberof DecisionResponse
     */
    reasons?: Array<ReasonDetail>;
    /**
     * 
     * @type {RiskBreakdown}
     * @memberof DecisionResponse
     */
    breakdown?: RiskBreakdown;
    /**
     * 
     * @type {DecisionResponsePolicy}
     * @memberof DecisionResponse
     */
    policy?: DecisionResponsePolicy;
}

/**
* @export
* @enum {string}
*/
export enum DecisionResponseDecisionEnum {
    Approve = 'approve',
    Review = 'review',
    Decline = 'decline',
    StepUp = 'step_up'
}


/**
 * Check if a given object implements the DecisionResponse interface.
 */
export function instanceOfDecisionResponse(value: object): value is DecisionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('decisionAt' in value) || value['decisionAt'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    return true;
}

export function DecisionResponseFromJSON(json: any): DecisionResponse {
    return DecisionResponseFromJSONTyped(json, false);
}

export function DecisionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'decision': json['decision'],
        'decisionAt': json['decisionAt'],
        'riskScore': json['riskScore'],
        'reasons': json['reasons'] == null ? undefined : ((json['reasons'] as Array<any>).map(ReasonDetailFromJSON)),
        'breakdown': json['breakdown'] == null ? undefined : RiskBreakdownFromJSON(json['breakdown']),
        'policy': json['policy'] == null ? undefined : DecisionResponsePolicyFromJSON(json['policy']),
    };
}

export function DecisionResponseToJSON(json: any): DecisionResponse {
    return DecisionResponseToJSONTyped(json, false);
}

export function DecisionResponseToJSONTyped(value?: DecisionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'decision': value['decision'],
        'decisionAt': value['decisionAt'],
        'riskScore': value['riskScore'],
        'reasons': value['reasons'] == null ? undefined : ((value['reasons'] as Array<any>).map(ReasonDetailToJSON)),
        'breakdown': RiskBreakdownToJSON(value['breakdown']),
        'policy': DecisionResponsePolicyToJSON(value['policy']),
    };
}

