/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionResolutionRequestAnalyst
 */
export interface DecisionResolutionRequestAnalyst {
    /**
     * The unique ID of the operator, SRE, or autonomous agent.
     * @type {string}
     * @memberof DecisionResolutionRequestAnalyst
     */
    id: string;
    /**
     * The system role of the decision maker.
     * @type {string}
     * @memberof DecisionResolutionRequestAnalyst
     */
    type: DecisionResolutionRequestAnalystTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum DecisionResolutionRequestAnalystTypeEnum {
    HumanMerchant = 'human_merchant',
    AutomatedConsensus = 'automated_consensus',
    AutonomousAgent = 'autonomous_agent'
}


/**
 * Check if a given object implements the DecisionResolutionRequestAnalyst interface.
 */
export function instanceOfDecisionResolutionRequestAnalyst(value: object): value is DecisionResolutionRequestAnalyst {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function DecisionResolutionRequestAnalystFromJSON(json: any): DecisionResolutionRequestAnalyst {
    return DecisionResolutionRequestAnalystFromJSONTyped(json, false);
}

export function DecisionResolutionRequestAnalystFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionResolutionRequestAnalyst {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
    };
}

export function DecisionResolutionRequestAnalystToJSON(json: any): DecisionResolutionRequestAnalyst {
    return DecisionResolutionRequestAnalystToJSONTyped(json, false);
}

export function DecisionResolutionRequestAnalystToJSONTyped(value?: DecisionResolutionRequestAnalyst | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
    };
}

