/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecisionResolutionResponse
 */
export interface DecisionResolutionResponse {
    /**
     * Indicates if the decision was successfully resolved and persisted.
     * @type {boolean}
     * @memberof DecisionResolutionResponse
     */
    ok: boolean;
    /**
     * Operational summary message.
     * @type {string}
     * @memberof DecisionResolutionResponse
     */
    message: string;
    /**
     * ISO-8601 timestamp of resolution completion.
     * @type {Date}
     * @memberof DecisionResolutionResponse
     */
    resolvedAt: Date;
}

/**
 * Check if a given object implements the DecisionResolutionResponse interface.
 */
export function instanceOfDecisionResolutionResponse(value: object): value is DecisionResolutionResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('resolvedAt' in value) || value['resolvedAt'] === undefined) return false;
    return true;
}

export function DecisionResolutionResponseFromJSON(json: any): DecisionResolutionResponse {
    return DecisionResolutionResponseFromJSONTyped(json, false);
}

export function DecisionResolutionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecisionResolutionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'message': json['message'],
        'resolvedAt': (new Date(json['resolvedAt'])),
    };
}

export function DecisionResolutionResponseToJSON(json: any): DecisionResolutionResponse {
    return DecisionResolutionResponseToJSONTyped(json, false);
}

export function DecisionResolutionResponseToJSONTyped(value?: DecisionResolutionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'message': value['message'],
        'resolvedAt': value['resolvedAt'].toISOString(),
    };
}

