/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IpInfo } from './IpInfo';
import {
    IpInfoFromJSON,
    IpInfoFromJSONTyped,
    IpInfoToJSON,
    IpInfoToJSONTyped,
} from './IpInfo';
import type { Integrity } from './Integrity';
import {
    IntegrityFromJSON,
    IntegrityFromJSONTyped,
    IntegrityToJSON,
    IntegrityToJSONTyped,
} from './Integrity';

/**
 * Aggregated device fingerprinting and behavioral patterns used for fraud detection.
 * @export
 * @interface DeviceInfo
 */
export interface DeviceInfo {
    /**
     * Unique hash representing the device's fingerprint. Lowercase hex. Prefix "fp_".
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    fingerprint?: string;
    /**
     * Browser's User-Agent string, useful for identifying OS and browser type.  Must be between 10 and 512 printable ASCII characters.
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    userAgent?: string;
    /**
     * 
     * @type {IpInfo}
     * @memberof DeviceInfo
     */
    ip?: IpInfo;
    /**
     * 
     * @type {Integrity}
     * @memberof DeviceInfo
     */
    integrity?: Integrity;
}

/**
 * Check if a given object implements the DeviceInfo interface.
 */
export function instanceOfDeviceInfo(value: object): value is DeviceInfo {
    return true;
}

export function DeviceInfoFromJSON(json: any): DeviceInfo {
    return DeviceInfoFromJSONTyped(json, false);
}

export function DeviceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'ip': json['ip'] == null ? undefined : IpInfoFromJSON(json['ip']),
        'integrity': json['integrity'] == null ? undefined : IntegrityFromJSON(json['integrity']),
    };
}

export function DeviceInfoToJSON(json: any): DeviceInfo {
    return DeviceInfoToJSONTyped(json, false);
}

export function DeviceInfoToJSONTyped(value?: DeviceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fingerprint': value['fingerprint'],
        'userAgent': value['userAgent'],
        'ip': IpInfoToJSON(value['ip']),
        'integrity': IntegrityToJSON(value['integrity']),
    };
}

