/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IpInfo } from './IpInfo';
import {
    IpInfoFromJSON,
    IpInfoFromJSONTyped,
    IpInfoToJSON,
    IpInfoToJSONTyped,
} from './IpInfo';
import type { Integrity } from './Integrity';
import {
    IntegrityFromJSON,
    IntegrityFromJSONTyped,
    IntegrityToJSON,
    IntegrityToJSONTyped,
} from './Integrity';

/**
 * Aggregated device fingerprinting and behavioral patterns used for fraud detection.
 * @export
 * @interface DeviceInfo
 */
export interface DeviceInfo {
    /**
     * Unique hash representing the device's fingerprint. Lowercase hex. Prefix "fp_".
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    fingerprint?: string;
    /**
     * Browser's User-Agent string, useful for identifying OS and browser type.  Must be between 10 and 512 printable ASCII characters.
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    userAgent?: string;
    /**
     * 
     * @type {IpInfo}
     * @memberof DeviceInfo
     */
    ip?: IpInfo;
    /**
     * 
     * @type {Integrity}
     * @memberof DeviceInfo
     */
    integrity?: Integrity;
}

/**
 * Check if a given object implements the DeviceInfo interface.
 */
export function instanceOfDeviceInfo(value: object): value is DeviceInfo {
    return true;
}

export function DeviceInfoFromJSON(json: any): DeviceInfo {
    return DeviceInfoFromJSONTyped(json, false);
}

export function DeviceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'fingerprint': json['fingerprint'] == null ? undefined : json['fingerprint'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'ip': json['ip'] == null ? undefined : IpInfoFromJSON(json['ip']),
        'integrity': json['integrity'] == null ? undefined : IntegrityFromJSON(json['integrity']),
    };
}

export function DeviceInfoToJSON(json: any): DeviceInfo {
    return DeviceInfoToJSONTyped(json, false);
}

export function DeviceInfoToJSONTyped(value?: DeviceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fingerprint': value['fingerprint'],
        'userAgent': value['userAgent'],
        'ip': IpInfoToJSON(value['ip']),
        'integrity': IntegrityToJSON(value['integrity']),
    };
}

