/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscountCode
 */
export interface DiscountCode {
    /**
     * The discount code string (e.g., 'SUMMER20').
     * @type {string}
     * @memberof DiscountCode
     */
    code: string;
    /**
     * The monetary value saved by this discount.
     * @type {number}
     * @memberof DiscountCode
     */
    amount?: number;
    /**
     * The type of discount applied.
     * @type {string}
     * @memberof DiscountCode
     */
    type?: DiscountCodeTypeEnum;
    /**
     * Optional: The number of times a single user/device is allowed to use this specific code.
     * @type {number}
     * @memberof DiscountCode
     */
    usageLimitPerUser?: number;
}

/**
* @export
* @enum {string}
*/
export enum DiscountCodeTypeEnum {
    Percentage = 'percentage',
    FixedAmount = 'fixed_amount',
    FreeShipping = 'free_shipping',
    BuyXGetY = 'buy_x_get_y'
}


/**
 * Check if a given object implements the DiscountCode interface.
 */
export function instanceOfDiscountCode(value: object): value is DiscountCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function DiscountCodeFromJSON(json: any): DiscountCode {
    return DiscountCodeFromJSONTyped(json, false);
}

export function DiscountCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'type': json['type'] == null ? undefined : json['type'],
        'usageLimitPerUser': json['usageLimitPerUser'] == null ? undefined : json['usageLimitPerUser'],
    };
}

export function DiscountCodeToJSON(json: any): DiscountCode {
    return DiscountCodeToJSONTyped(json, false);
}

export function DiscountCodeToJSONTyped(value?: DiscountCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'amount': value['amount'],
        'type': value['type'],
        'usageLimitPerUser': value['usageLimitPerUser'],
    };
}

