/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiscountCode
 */
export interface DiscountCode {
    /**
     * The discount code string (e.g., 'SUMMER20').
     * @type {string}
     * @memberof DiscountCode
     */
    code: string;
    /**
     * The monetary value saved by this discount.
     * @type {number}
     * @memberof DiscountCode
     */
    amount?: number;
    /**
     * The type of discount applied.
     * @type {string}
     * @memberof DiscountCode
     */
    type?: DiscountCodeTypeEnum;
    /**
     * Optional: The number of times a single user/device is allowed to use this specific code.
     * @type {number}
     * @memberof DiscountCode
     */
    usageLimitPerUser?: number;
}

/**
* @export
* @enum {string}
*/
export enum DiscountCodeTypeEnum {
    Percentage = 'percentage',
    FixedAmount = 'fixed_amount',
    FreeShipping = 'free_shipping',
    BuyXGetY = 'buy_x_get_y'
}


/**
 * Check if a given object implements the DiscountCode interface.
 */
export function instanceOfDiscountCode(value: object): value is DiscountCode {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function DiscountCodeFromJSON(json: any): DiscountCode {
    return DiscountCodeFromJSONTyped(json, false);
}

export function DiscountCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'type': json['type'] == null ? undefined : json['type'],
        'usageLimitPerUser': json['usageLimitPerUser'] == null ? undefined : json['usageLimitPerUser'],
    };
}

export function DiscountCodeToJSON(json: any): DiscountCode {
    return DiscountCodeToJSONTyped(json, false);
}

export function DiscountCodeToJSONTyped(value?: DiscountCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'amount': value['amount'],
        'type': value['type'],
        'usageLimitPerUser': value['usageLimitPerUser'],
    };
}

