/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Canonical entity identifiers (tenant/client/user/device/session). Do not send raw PII. Hash emails/phones/addresses as sha256 and prefix with 'sha256_'.
 * Tiered support:
 *   - tenantId is the top-level SaaS customer (required for all flows).
 *   - clientId is the tenant's downstream business customer (e.g. merchant/partner) and MAY be omitted for
 *     processor / bank / PSP-style integrations.
 *   - endCustomerId is the tenant/client's consumer or business account (cardholder, shopper, etc.) and
 *     MAY be omitted for purely device- or instrument-level checks.
 * 
 * @export
 * @interface EntityIds
 */
export interface EntityIds {
    /**
     * Canonical ID for the paying organization (Tenant). Opaque, immutable, lowercase.  Must start with "tid_". Do not use domains or emails here. For a tenant's domain,  use a separate field (e.g., tenantDomain).
     * 
     * @type {string}
     * @memberof EntityIds
     */
    tenantId?: string;
    /**
     * Canonical ID for the Tenant’s business customer (e.g., merchant/partner).  Opaque, immutable, lowercase. Must start with 'cid_'.
     * 
     * @type {string}
     * @memberof EntityIds
     */
    clientId?: string;
    /**
     * Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Must start with "ecid_".  Do not put PII (like emails or phone numbers) in this field.
     * 
     * @type {string}
     * @memberof EntityIds
     */
    endCustomerId?: string;
    /**
     * Canonical ID for a Tenant member/operator (employee/contractor) using the platform.  Opaque, immutable, lowercase. Must start with 'mid_'.
     * 
     * @type {string}
     * @memberof EntityIds
     */
    memberId?: string;
    /**
     * Tokenized instrument ID (non-PCI).
     * @type {string}
     * @memberof EntityIds
     */
    paymentInstrumentId?: string;
    /**
     * Server-issued stable device token (device-level identifier).
     * Should persist across sessions and logins on the same browser/device.
     * 
     * @type {string}
     * @memberof EntityIds
     */
    deviceId?: string;
    /**
     * Application/user session identifier (login or checkout session).
     * Typically rotates more frequently than deviceId and may be tied to authentication.
     * 
     * @type {string}
     * @memberof EntityIds
     */
    sessionId?: string;
    /**
     * Normalized+lowercased email hash (e.g., sha256).
     * @type {string}
     * @memberof EntityIds
     */
    emailHash?: string;
    /**
     * Normalized+lowercased email *domain* hash (e.g., sha256).
     * @type {string}
     * @memberof EntityIds
     */
    emailDomainHash?: string;
    /**
     * Normalized+lowercased phone hash (e.g., sha256).
     * @type {string}
     * @memberof EntityIds
     */
    phoneHash?: string;
    /**
     * Normalized+lowercased shipping address hash (e.g., sha256).
     * @type {string}
     * @memberof EntityIds
     */
    shippingAddressHash?: string;
    /**
     * Normalized+lowercased billing address hash (e.g., sha256).
     * @type {string}
     * @memberof EntityIds
     */
    billingAddressHash?: string;
}

/**
 * Check if a given object implements the EntityIds interface.
 */
export function instanceOfEntityIds(value: object): value is EntityIds {
    return true;
}

export function EntityIdsFromJSON(json: any): EntityIds {
    return EntityIdsFromJSONTyped(json, false);
}

export function EntityIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityIds {
    if (json == null) {
        return json;
    }
    return {
        
        'tenantId': json['tenantId'] == null ? undefined : json['tenantId'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'endCustomerId': json['endCustomerId'] == null ? undefined : json['endCustomerId'],
        'memberId': json['memberId'] == null ? undefined : json['memberId'],
        'paymentInstrumentId': json['paymentInstrumentId'] == null ? undefined : json['paymentInstrumentId'],
        'deviceId': json['deviceId'] == null ? undefined : json['deviceId'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'emailHash': json['emailHash'] == null ? undefined : json['emailHash'],
        'emailDomainHash': json['emailDomainHash'] == null ? undefined : json['emailDomainHash'],
        'phoneHash': json['phoneHash'] == null ? undefined : json['phoneHash'],
        'shippingAddressHash': json['shippingAddressHash'] == null ? undefined : json['shippingAddressHash'],
        'billingAddressHash': json['billingAddressHash'] == null ? undefined : json['billingAddressHash'],
    };
}

export function EntityIdsToJSON(json: any): EntityIds {
    return EntityIdsToJSONTyped(json, false);
}

export function EntityIdsToJSONTyped(value?: EntityIds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenantId': value['tenantId'],
        'clientId': value['clientId'],
        'endCustomerId': value['endCustomerId'],
        'memberId': value['memberId'],
        'paymentInstrumentId': value['paymentInstrumentId'],
        'deviceId': value['deviceId'],
        'sessionId': value['sessionId'],
        'emailHash': value['emailHash'],
        'emailDomainHash': value['emailDomainHash'],
        'phoneHash': value['phoneHash'],
        'shippingAddressHash': value['shippingAddressHash'],
        'billingAddressHash': value['billingAddressHash'],
    };
}

