/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The method used to capture card data.
 * @export
 * @enum {string}
 */
export enum EntryMethodEnum {
    Chip = 'chip',
    Contactless = 'contactless',
    Magstripe = 'magstripe',
    ManualKeyed = 'manual_keyed',
    CardOnFile = 'card_on_file',
    WalletToken = 'wallet_token',
    NetworkToken = 'network_token'
}


export function instanceOfEntryMethodEnum(value: any): boolean {
    for (const key in EntryMethodEnum) {
        if (Object.prototype.hasOwnProperty.call(EntryMethodEnum, key)) {
            if (EntryMethodEnum[key as keyof typeof EntryMethodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EntryMethodEnumFromJSON(json: any): EntryMethodEnum {
    return EntryMethodEnumFromJSONTyped(json, false);
}

export function EntryMethodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryMethodEnum {
    return json as EntryMethodEnum;
}

export function EntryMethodEnumToJSON(value?: EntryMethodEnum | null): any {
    return value as any;
}

export function EntryMethodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): EntryMethodEnum {
    return value as EntryMethodEnum;
}
