/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskLevelEnum } from './RiskLevelEnum';
import {
    RiskLevelEnumFromJSON,
    RiskLevelEnumFromJSONTyped,
    RiskLevelEnumToJSON,
    RiskLevelEnumToJSONTyped,
} from './RiskLevelEnum';

/**
 * 
 * @export
 * @interface ExternalAssessment
 */
export interface ExternalAssessment {
    /**
     * The provider of the assessment (e.g., 'shopify', 'signifyd').
     * @type {string}
     * @memberof ExternalAssessment
     */
    source: string;
    /**
     * 
     * @type {RiskLevelEnum}
     * @memberof ExternalAssessment
     */
    level: RiskLevelEnum;
    /**
     * The raw score provided by the 3rd party (if applicable).
     * @type {number}
     * @memberof ExternalAssessment
     */
    score?: number;
    /**
     * The specific action recommended by the 3rd party.
     * @type {string}
     * @memberof ExternalAssessment
     */
    recommendation?: string;
    /**
     * Raw reason codes provided by the 3rd party vendor.
     * @type {Array<string>}
     * @memberof ExternalAssessment
     */
    reasonCodes?: Array<string>;
    /**
     * Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.
     * 
     * @type {string}
     * @memberof ExternalAssessment
     */
    metadata?: string;
}



/**
 * Check if a given object implements the ExternalAssessment interface.
 */
export function instanceOfExternalAssessment(value: object): value is ExternalAssessment {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function ExternalAssessmentFromJSON(json: any): ExternalAssessment {
    return ExternalAssessmentFromJSONTyped(json, false);
}

export function ExternalAssessmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalAssessment {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'],
        'level': RiskLevelEnumFromJSON(json['level']),
        'score': json['score'] == null ? undefined : json['score'],
        'recommendation': json['recommendation'] == null ? undefined : json['recommendation'],
        'reasonCodes': json['reasonCodes'] == null ? undefined : json['reasonCodes'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ExternalAssessmentToJSON(json: any): ExternalAssessment {
    return ExternalAssessmentToJSONTyped(json, false);
}

export function ExternalAssessmentToJSONTyped(value?: ExternalAssessment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'level': RiskLevelEnumToJSON(value['level']),
        'score': value['score'],
        'recommendation': value['recommendation'],
        'reasonCodes': value['reasonCodes'],
        'metadata': value['metadata'],
    };
}

