/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskLevelEnum } from './RiskLevelEnum';
import {
    RiskLevelEnumFromJSON,
    RiskLevelEnumFromJSONTyped,
    RiskLevelEnumToJSON,
    RiskLevelEnumToJSONTyped,
} from './RiskLevelEnum';
import type { ConfidenceEnum } from './ConfidenceEnum';
import {
    ConfidenceEnumFromJSON,
    ConfidenceEnumFromJSONTyped,
    ConfidenceEnumToJSON,
    ConfidenceEnumToJSONTyped,
} from './ConfidenceEnum';

/**
 * Fraud score for a specific transaction or entity.
 * @export
 * @interface FraudScore
 */
export interface FraudScore {
    /**
     * 
     * @type {RiskLevelEnum}
     * @memberof FraudScore
     */
    riskLevel: RiskLevelEnum;
    /**
     * 
     * @type {ConfidenceEnum}
     * @memberof FraudScore
     */
    confidence?: ConfidenceEnum;
    /**
     * Fraud risk score (0.00 - 1.00).
     * @type {number}
     * @memberof FraudScore
     */
    score?: number;
    /**
     * A human-readable explanation of the fraud score, if available.
     * @type {string}
     * @memberof FraudScore
     */
    explanation?: string;
}



/**
 * Check if a given object implements the FraudScore interface.
 */
export function instanceOfFraudScore(value: object): value is FraudScore {
    if (!('riskLevel' in value) || value['riskLevel'] === undefined) return false;
    return true;
}

export function FraudScoreFromJSON(json: any): FraudScore {
    return FraudScoreFromJSONTyped(json, false);
}

export function FraudScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): FraudScore {
    if (json == null) {
        return json;
    }
    return {
        
        'riskLevel': RiskLevelEnumFromJSON(json['riskLevel']),
        'confidence': json['confidence'] == null ? undefined : ConfidenceEnumFromJSON(json['confidence']),
        'score': json['score'] == null ? undefined : json['score'],
        'explanation': json['explanation'] == null ? undefined : json['explanation'],
    };
}

export function FraudScoreToJSON(json: any): FraudScore {
    return FraudScoreToJSONTyped(json, false);
}

export function FraudScoreToJSONTyped(value?: FraudScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'riskLevel': RiskLevelEnumToJSON(value['riskLevel']),
        'confidence': ConfidenceEnumToJSON(value['confidence']),
        'score': value['score'],
        'explanation': value['explanation'],
    };
}

