/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskLevelEnum } from './RiskLevelEnum';
import {
    RiskLevelEnumFromJSON,
    RiskLevelEnumFromJSONTyped,
    RiskLevelEnumToJSON,
    RiskLevelEnumToJSONTyped,
} from './RiskLevelEnum';
import type { ConfidenceEnum } from './ConfidenceEnum';
import {
    ConfidenceEnumFromJSON,
    ConfidenceEnumFromJSONTyped,
    ConfidenceEnumToJSON,
    ConfidenceEnumToJSONTyped,
} from './ConfidenceEnum';

/**
 * Fraud score for a specific transaction or entity.
 * @export
 * @interface FraudScore
 */
export interface FraudScore {
    /**
     * 
     * @type {RiskLevelEnum}
     * @memberof FraudScore
     */
    riskLevel: RiskLevelEnum;
    /**
     * 
     * @type {ConfidenceEnum}
     * @memberof FraudScore
     */
    confidence?: ConfidenceEnum;
    /**
     * Fraud risk score (0.00 - 1.00).
     * @type {number}
     * @memberof FraudScore
     */
    score?: number;
    /**
     * A human-readable explanation of the fraud score, if available.
     * @type {string}
     * @memberof FraudScore
     */
    explanation?: string;
}



/**
 * Check if a given object implements the FraudScore interface.
 */
export function instanceOfFraudScore(value: object): value is FraudScore {
    if (!('riskLevel' in value) || value['riskLevel'] === undefined) return false;
    return true;
}

export function FraudScoreFromJSON(json: any): FraudScore {
    return FraudScoreFromJSONTyped(json, false);
}

export function FraudScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): FraudScore {
    if (json == null) {
        return json;
    }
    return {
        
        'riskLevel': RiskLevelEnumFromJSON(json['riskLevel']),
        'confidence': json['confidence'] == null ? undefined : ConfidenceEnumFromJSON(json['confidence']),
        'score': json['score'] == null ? undefined : json['score'],
        'explanation': json['explanation'] == null ? undefined : json['explanation'],
    };
}

export function FraudScoreToJSON(json: any): FraudScore {
    return FraudScoreToJSONTyped(json, false);
}

export function FraudScoreToJSONTyped(value?: FraudScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'riskLevel': RiskLevelEnumToJSON(value['riskLevel']),
        'confidence': ConfidenceEnumToJSON(value['confidence']),
        'score': value['score'],
        'explanation': value['explanation'],
    };
}

