/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
    PostalAddressToJSONTyped,
} from './PostalAddress';

/**
 * Optional raw identity details for the account associated with the purchase.
 * These fields (email, phone, addresses) are used for normalization, hashing,
 * and risk feature extraction (e.g., email/phone/domain scoring, address risk),
 * and are not stored in raw form by Alogram.
 * 
 * When provided, Alogram will derive and/or cross-check:
 * - emailHash / phoneHash / shippingAddressHash / billingAddressHash
 *   in the internal entity model
 * - email/phone/domain risk signals
 * - address consistency and geo-distance checks
 * 
 * @export
 * @interface Identity
 */
export interface Identity {
    /**
     * Email address of the customer.
     * @type {string}
     * @memberof Identity
     */
    email?: string;
    /**
     * Email domain only (no local part). Useful for domain-level risk and
     * allow/deny lists without sending full email PII.
     * Example: "gmail.com", "merchant-example.co.uk"
     * 
     * @type {string}
     * @memberof Identity
     */
    emailDomain?: string;
    /**
     * Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: "+1 (415) 555-2671", "415-555-2671", "+14155552671"
     * 
     * @type {string}
     * @memberof Identity
     */
    phone?: string;
    /**
     * 
     * @type {PostalAddress}
     * @memberof Identity
     */
    shippingAddress?: PostalAddress;
    /**
     * 
     * @type {PostalAddress}
     * @memberof Identity
     */
    billingAddress?: PostalAddress;
    /**
     * Optional: Set to true if client-side bot detection (e.g. reCAPTCHA) triggered.
     * @type {boolean}
     * @memberof Identity
     */
    isBot?: boolean;
    /**
     * Optional: Client-side assessment of email reputation.
     * @type {string}
     * @memberof Identity
     */
    emailReputation?: IdentityEmailReputationEnum;
}

/**
* @export
* @enum {string}
*/
export enum IdentityEmailReputationEnum {
    Low = 'low',
    Medium = 'medium',
    High = 'high'
}


/**
 * Check if a given object implements the Identity interface.
 */
export function instanceOfIdentity(value: object): value is Identity {
    return true;
}

export function IdentityFromJSON(json: any): Identity {
    return IdentityFromJSONTyped(json, false);
}

export function IdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Identity {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'emailDomain': json['emailDomain'] == null ? undefined : json['emailDomain'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'shippingAddress': json['shippingAddress'] == null ? undefined : PostalAddressFromJSON(json['shippingAddress']),
        'billingAddress': json['billingAddress'] == null ? undefined : PostalAddressFromJSON(json['billingAddress']),
        'isBot': json['isBot'] == null ? undefined : json['isBot'],
        'emailReputation': json['emailReputation'] == null ? undefined : json['emailReputation'],
    };
}

export function IdentityToJSON(json: any): Identity {
    return IdentityToJSONTyped(json, false);
}

export function IdentityToJSONTyped(value?: Identity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'emailDomain': value['emailDomain'],
        'phone': value['phone'],
        'shippingAddress': PostalAddressToJSON(value['shippingAddress']),
        'billingAddress': PostalAddressToJSON(value['billingAddress']),
        'isBot': value['isBot'],
        'emailReputation': value['emailReputation'],
    };
}

