/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
    PostalAddressToJSONTyped,
} from './PostalAddress';

/**
 * Optional raw identity details for the account associated with the purchase.
 * These fields (email, phone, addresses) are used for normalization, hashing,
 * and risk feature extraction (e.g., email/phone/domain scoring, address risk),
 * and are not stored in raw form by Alogram.
 * 
 * When provided, Alogram will derive and/or cross-check:
 * - emailHash / phoneHash / shippingAddressHash / billingAddressHash
 *   in the internal entity model
 * - email/phone/domain risk signals
 * - address consistency and geo-distance checks
 * 
 * @export
 * @interface Identity
 */
export interface Identity {
    /**
     * Email address of the customer.
     * @type {string}
     * @memberof Identity
     */
    email?: string;
    /**
     * Email domain only (no local part). Useful for domain-level risk and
     * allow/deny lists without sending full email PII.
     * Example: "gmail.com", "merchant-example.co.uk"
     * 
     * @type {string}
     * @memberof Identity
     */
    emailDomain?: string;
    /**
     * Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: "+1 (415) 555-2671", "415-555-2671", "+14155552671"
     * 
     * @type {string}
     * @memberof Identity
     */
    phone?: string;
    /**
     * 
     * @type {PostalAddress}
     * @memberof Identity
     */
    shippingAddress?: PostalAddress;
    /**
     * 
     * @type {PostalAddress}
     * @memberof Identity
     */
    billingAddress?: PostalAddress;
}

/**
 * Check if a given object implements the Identity interface.
 */
export function instanceOfIdentity(value: object): value is Identity {
    return true;
}

export function IdentityFromJSON(json: any): Identity {
    return IdentityFromJSONTyped(json, false);
}

export function IdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Identity {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'emailDomain': json['emailDomain'] == null ? undefined : json['emailDomain'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'shippingAddress': json['shippingAddress'] == null ? undefined : PostalAddressFromJSON(json['shippingAddress']),
        'billingAddress': json['billingAddress'] == null ? undefined : PostalAddressFromJSON(json['billingAddress']),
    };
}

export function IdentityToJSON(json: any): Identity {
    return IdentityToJSONTyped(json, false);
}

export function IdentityToJSONTyped(value?: Identity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'emailDomain': value['emailDomain'],
        'phone': value['phone'],
        'shippingAddress': PostalAddressToJSON(value['shippingAddress']),
        'billingAddress': PostalAddressToJSON(value['billingAddress']),
    };
}

