/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.3.2
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngestPaymentEvent202Response
 */
export interface IngestPaymentEvent202Response {
    /**
     * 
     * @type {string}
     * @memberof IngestPaymentEvent202Response
     */
    status?: string;
}

/**
 * Check if a given object implements the IngestPaymentEvent202Response interface.
 */
export function instanceOfIngestPaymentEvent202Response(value: object): value is IngestPaymentEvent202Response {
    return true;
}

export function IngestPaymentEvent202ResponseFromJSON(json: any): IngestPaymentEvent202Response {
    return IngestPaymentEvent202ResponseFromJSONTyped(json, false);
}

export function IngestPaymentEvent202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngestPaymentEvent202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function IngestPaymentEvent202ResponseToJSON(json: any): IngestPaymentEvent202Response {
    return IngestPaymentEvent202ResponseToJSONTyped(json, false);
}

export function IngestPaymentEvent202ResponseToJSONTyped(value?: IngestPaymentEvent202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

