/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of interaction being recorded.
 * @export
 * @enum {string}
 */
export enum InteractionTypeEnum {
    Login = 'login',
    FeatureUse = 'feature_use',
    SettingChange = 'setting_change',
    PageView = 'page_view',
    _3rdPartyEvent = '3rd_party_event',
    CustomEvent = 'custom_event'
}


export function instanceOfInteractionTypeEnum(value: any): boolean {
    for (const key in InteractionTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(InteractionTypeEnum, key)) {
            if (InteractionTypeEnum[key as keyof typeof InteractionTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InteractionTypeEnumFromJSON(json: any): InteractionTypeEnum {
    return InteractionTypeEnumFromJSONTyped(json, false);
}

export function InteractionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionTypeEnum {
    return json as InteractionTypeEnum;
}

export function InteractionTypeEnumToJSON(value?: InteractionTypeEnum | null): any {
    return value as any;
}

export function InteractionTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): InteractionTypeEnum {
    return value as InteractionTypeEnum;
}
