/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of interaction being recorded.
 * @export
 * @enum {string}
 */
export enum InteractionTypeEnum {
    Login = 'login',
    FeatureUse = 'feature_use',
    SettingChange = 'setting_change',
    PageView = 'page_view',
    _3rdPartyEvent = '3rd_party_event',
    CustomEvent = 'custom_event'
}


export function instanceOfInteractionTypeEnum(value: any): boolean {
    for (const key in InteractionTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(InteractionTypeEnum, key)) {
            if (InteractionTypeEnum[key as keyof typeof InteractionTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InteractionTypeEnumFromJSON(json: any): InteractionTypeEnum {
    return InteractionTypeEnumFromJSONTyped(json, false);
}

export function InteractionTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): InteractionTypeEnum {
    return json as InteractionTypeEnum;
}

export function InteractionTypeEnumToJSON(value?: InteractionTypeEnum | null): any {
    return value as any;
}

export function InteractionTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): InteractionTypeEnum {
    return value as InteractionTypeEnum;
}

