/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Integrity
 */
export interface Integrity {
    /**
     * Indicates whether the IP address is associated with a proxy, VPN, or Tor exit node.
     * 
     * @type {boolean}
     * @memberof Integrity
     */
    isProxyVpnTor?: boolean;
    /**
     * Indicates whether the IP address belongs to a hosting provider (e.g., data center, cloud provider).
     * 
     * @type {boolean}
     * @memberof Integrity
     */
    isHostingProvider?: boolean;
    /**
     * Indicates whether the browser is running in headless mode (e.g., automated testing, scraping).
     * 
     * @type {boolean}
     * @memberof Integrity
     */
    isHeadless?: boolean;
    /**
     * Indicates whether the request originated from an automated script or bot.
     * 
     * @type {boolean}
     * @memberof Integrity
     */
    isAutomation?: boolean;
    /**
     * Indicates whether the request originated from an emulator (e.g., Android Emulator, iOS Simulator).
     * 
     * @type {boolean}
     * @memberof Integrity
     */
    isEmulator?: boolean;
    /**
     * Indicates whether the device is rooted (Android) or jailbroken (iOS).
     * 
     * @type {boolean}
     * @memberof Integrity
     */
    isRootedJailbroken?: boolean;
}

/**
 * Check if a given object implements the Integrity interface.
 */
export function instanceOfIntegrity(value: object): value is Integrity {
    return true;
}

export function IntegrityFromJSON(json: any): Integrity {
    return IntegrityFromJSONTyped(json, false);
}

export function IntegrityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Integrity {
    if (json == null) {
        return json;
    }
    return {
        
        'isProxyVpnTor': json['isProxyVpnTor'] == null ? undefined : json['isProxyVpnTor'],
        'isHostingProvider': json['isHostingProvider'] == null ? undefined : json['isHostingProvider'],
        'isHeadless': json['isHeadless'] == null ? undefined : json['isHeadless'],
        'isAutomation': json['isAutomation'] == null ? undefined : json['isAutomation'],
        'isEmulator': json['isEmulator'] == null ? undefined : json['isEmulator'],
        'isRootedJailbroken': json['isRootedJailbroken'] == null ? undefined : json['isRootedJailbroken'],
    };
}

export function IntegrityToJSON(json: any): Integrity {
    return IntegrityToJSONTyped(json, false);
}

export function IntegrityToJSONTyped(value?: Integrity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isProxyVpnTor': value['isProxyVpnTor'],
        'isHostingProvider': value['isHostingProvider'],
        'isHeadless': value['isHeadless'],
        'isAutomation': value['isAutomation'],
        'isEmulator': value['isEmulator'],
        'isRootedJailbroken': value['isRootedJailbroken'],
    };
}

