/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceInfo } from './DeviceInfo';
import {
    DeviceInfoFromJSON,
    DeviceInfoFromJSONTyped,
    DeviceInfoToJSON,
    DeviceInfoToJSONTyped,
} from './DeviceInfo';
import type { InteractionTypeEnum } from './InteractionTypeEnum';
import {
    InteractionTypeEnumFromJSON,
    InteractionTypeEnumFromJSONTyped,
    InteractionTypeEnumToJSON,
    InteractionTypeEnumToJSONTyped,
} from './InteractionTypeEnum';

/**
 * The application-layer Interaction object.
 * @export
 * @interface Interaction
 */
export interface Interaction {
    /**
     * Unique identifier for the location where the transaction occurred.
     * @type {string}
     * @memberof Interaction
     */
    locationId?: string;
    /**
     * 
     * @type {DeviceInfo}
     * @memberof Interaction
     */
    deviceInfo?: DeviceInfo;
    /**
     * RFC 3339 timestamp with timezone.
     * @type {string}
     * @memberof Interaction
     */
    timestamp?: string;
    /**
     * 
     * @type {InteractionTypeEnum}
     * @memberof Interaction
     */
    interactionType: InteractionTypeEnum;
    /**
     * Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.
     * 
     * @type {string}
     * @memberof Interaction
     */
    metadata?: string;
}



/**
 * Check if a given object implements the Interaction interface.
 */
export function instanceOfInteraction(value: object): value is Interaction {
    if (!('interactionType' in value) || value['interactionType'] === undefined) return false;
    return true;
}

export function InteractionFromJSON(json: any): Interaction {
    return InteractionFromJSONTyped(json, false);
}

export function InteractionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Interaction {
    if (json == null) {
        return json;
    }
    return {
        
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'deviceInfo': json['deviceInfo'] == null ? undefined : DeviceInfoFromJSON(json['deviceInfo']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'interactionType': InteractionTypeEnumFromJSON(json['interactionType']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function InteractionToJSON(json: any): Interaction {
    return InteractionToJSONTyped(json, false);
}

export function InteractionToJSONTyped(value?: Interaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationId': value['locationId'],
        'deviceInfo': DeviceInfoToJSON(value['deviceInfo']),
        'timestamp': value['timestamp'],
        'interactionType': InteractionTypeEnumToJSON(value['interactionType']),
        'metadata': value['metadata'],
    };
}

