/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IpInfo
 */
export interface IpInfo {
    /**
     * IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255.
     * 
     * @type {string}
     * @memberof IpInfo
     */
    ipAddress?: string;
    /**
     * IPv6 address.
     * @type {string}
     * @memberof IpInfo
     */
    ipv6?: string;
    /**
     * IP protocol version.
     * @type {string}
     * @memberof IpInfo
     */
    ipVersion?: IpInfoIpVersionEnum;
    /**
     * CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48
     * @type {string}
     * @memberof IpInfo
     */
    ipPrefix?: string;
    /**
     * Autonomous System Number (ASN) of the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    asn?: string;
    /**
     * Organization associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    org?: string;
    /**
     * Company associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    company?: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof IpInfo
     */
    country?: string;
    /**
     * Region associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    region?: string;
    /**
     * City associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    city?: string;
    /**
     * Postal code associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    postalCode?: string;
}

/**
* @export
* @enum {string}
*/
export enum IpInfoIpVersionEnum {
    Ipv4 = 'ipv4',
    Ipv6 = 'ipv6'
}


/**
 * Check if a given object implements the IpInfo interface.
 */
export function instanceOfIpInfo(value: object): value is IpInfo {
    return true;
}

export function IpInfoFromJSON(json: any): IpInfo {
    return IpInfoFromJSONTyped(json, false);
}

export function IpInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'ipv6': json['ipv6'] == null ? undefined : json['ipv6'],
        'ipVersion': json['ipVersion'] == null ? undefined : json['ipVersion'],
        'ipPrefix': json['ipPrefix'] == null ? undefined : json['ipPrefix'],
        'asn': json['asn'] == null ? undefined : json['asn'],
        'org': json['org'] == null ? undefined : json['org'],
        'company': json['company'] == null ? undefined : json['company'],
        'country': json['country'] == null ? undefined : json['country'],
        'region': json['region'] == null ? undefined : json['region'],
        'city': json['city'] == null ? undefined : json['city'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
    };
}

export function IpInfoToJSON(json: any): IpInfo {
    return IpInfoToJSONTyped(json, false);
}

export function IpInfoToJSONTyped(value?: IpInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ipAddress': value['ipAddress'],
        'ipv6': value['ipv6'],
        'ipVersion': value['ipVersion'],
        'ipPrefix': value['ipPrefix'],
        'asn': value['asn'],
        'org': value['org'],
        'company': value['company'],
        'country': value['country'],
        'region': value['region'],
        'city': value['city'],
        'postalCode': value['postalCode'],
    };
}

