/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IpInfo
 */
export interface IpInfo {
    /**
     * IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255.
     * 
     * @type {string}
     * @memberof IpInfo
     */
    ipAddress?: string;
    /**
     * IPv6 address.
     * @type {string}
     * @memberof IpInfo
     */
    ipv6?: string;
    /**
     * IP protocol version.
     * @type {string}
     * @memberof IpInfo
     */
    ipVersion?: IpInfoIpVersionEnum;
    /**
     * CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48
     * @type {string}
     * @memberof IpInfo
     */
    ipPrefix?: string;
    /**
     * Autonomous System Number (ASN) of the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    asn?: string;
    /**
     * Organization associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    org?: string;
    /**
     * Company associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    company?: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof IpInfo
     */
    country?: string;
    /**
     * Region associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    region?: string;
    /**
     * City associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    city?: string;
    /**
     * Postal code associated with the IP address.
     * @type {string}
     * @memberof IpInfo
     */
    postalCode?: string;
}

/**
* @export
* @enum {string}
*/
export enum IpInfoIpVersionEnum {
    Ipv4 = 'ipv4',
    Ipv6 = 'ipv6'
}


/**
 * Check if a given object implements the IpInfo interface.
 */
export function instanceOfIpInfo(value: object): value is IpInfo {
    return true;
}

export function IpInfoFromJSON(json: any): IpInfo {
    return IpInfoFromJSONTyped(json, false);
}

export function IpInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'ipv6': json['ipv6'] == null ? undefined : json['ipv6'],
        'ipVersion': json['ipVersion'] == null ? undefined : json['ipVersion'],
        'ipPrefix': json['ipPrefix'] == null ? undefined : json['ipPrefix'],
        'asn': json['asn'] == null ? undefined : json['asn'],
        'org': json['org'] == null ? undefined : json['org'],
        'company': json['company'] == null ? undefined : json['company'],
        'country': json['country'] == null ? undefined : json['country'],
        'region': json['region'] == null ? undefined : json['region'],
        'city': json['city'] == null ? undefined : json['city'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
    };
}

export function IpInfoToJSON(json: any): IpInfo {
    return IpInfoToJSONTyped(json, false);
}

export function IpInfoToJSONTyped(value?: IpInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ipAddress': value['ipAddress'],
        'ipv6': value['ipv6'],
        'ipVersion': value['ipVersion'],
        'ipPrefix': value['ipPrefix'],
        'asn': value['asn'],
        'org': value['org'],
        'company': value['company'],
        'country': value['country'],
        'region': value['region'],
        'city': value['city'],
        'postalCode': value['postalCode'],
    };
}
