/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Merchant context for the purchase.
 * @export
 * @interface MerchantContext
 */
export interface MerchantContext {
    /**
     * Merchant Category Code (MCC) for the merchant.
     * @type {string}
     * @memberof MerchantContext
     */
    mcc?: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof MerchantContext
     */
    merchantCountry?: string;
}

/**
 * Check if a given object implements the MerchantContext interface.
 */
export function instanceOfMerchantContext(value: object): value is MerchantContext {
    return true;
}

export function MerchantContextFromJSON(json: any): MerchantContext {
    return MerchantContextFromJSONTyped(json, false);
}

export function MerchantContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantContext {
    if (json == null) {
        return json;
    }
    return {
        
        'mcc': json['mcc'] == null ? undefined : json['mcc'],
        'merchantCountry': json['merchantCountry'] == null ? undefined : json['merchantCountry'],
    };
}

export function MerchantContextToJSON(json: any): MerchantContext {
    return MerchantContextToJSONTyped(json, false);
}

export function MerchantContextToJSONTyped(value?: MerchantContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mcc': value['mcc'],
        'merchantCountry': value['merchantCountry'],
    };
}

