/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Order context for the purchase.
 * @export
 * @interface OrderContext
 */
export interface OrderContext {
    /**
     * Unique identifier for the order.
     * @type {string}
     * @memberof OrderContext
     */
    orderId?: string;
    /**
     * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.
     * 
     * @type {number}
     * @memberof OrderContext
     */
    orderTotal?: number;
    /**
     * Shipping method for the order.
     * @type {string}
     * @memberof OrderContext
     */
    shippingMethod?: OrderContextShippingMethodEnum;
    /**
     * Number of items in the order.
     * @type {number}
     * @memberof OrderContext
     */
    lineItemCount?: number;
}

/**
* @export
* @enum {string}
*/
export enum OrderContextShippingMethodEnum {
    Digital = 'digital',
    Ship = 'ship',
    Bopis = 'bopis'
}


/**
 * Check if a given object implements the OrderContext interface.
 */
export function instanceOfOrderContext(value: object): value is OrderContext {
    return true;
}

export function OrderContextFromJSON(json: any): OrderContext {
    return OrderContextFromJSONTyped(json, false);
}

export function OrderContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderContext {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'orderTotal': json['orderTotal'] == null ? undefined : json['orderTotal'],
        'shippingMethod': json['shippingMethod'] == null ? undefined : json['shippingMethod'],
        'lineItemCount': json['lineItemCount'] == null ? undefined : json['lineItemCount'],
    };
}

export function OrderContextToJSON(json: any): OrderContext {
    return OrderContextToJSONTyped(json, false);
}

export function OrderContextToJSONTyped(value?: OrderContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'orderTotal': value['orderTotal'],
        'shippingMethod': value['shippingMethod'],
        'lineItemCount': value['lineItemCount'],
    };
}

