/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Order context for the purchase.
 * @export
 * @interface OrderContext
 */
export interface OrderContext {
    /**
     * Unique identifier for the order.
     * @type {string}
     * @memberof OrderContext
     */
    orderId?: string;
    /**
     * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.
     * 
     * @type {number}
     * @memberof OrderContext
     */
    orderTotal?: number;
    /**
     * Shipping method for the order.
     * @type {string}
     * @memberof OrderContext
     */
    shippingMethod?: OrderContextShippingMethodEnum;
    /**
     * Number of items in the order.
     * @type {number}
     * @memberof OrderContext
     */
    lineItemCount?: number;
}

/**
* @export
* @enum {string}
*/
export enum OrderContextShippingMethodEnum {
    Digital = 'digital',
    Ship = 'ship',
    Bopis = 'bopis'
}


/**
 * Check if a given object implements the OrderContext interface.
 */
export function instanceOfOrderContext(value: object): value is OrderContext {
    return true;
}

export function OrderContextFromJSON(json: any): OrderContext {
    return OrderContextFromJSONTyped(json, false);
}

export function OrderContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderContext {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'orderTotal': json['orderTotal'] == null ? undefined : json['orderTotal'],
        'shippingMethod': json['shippingMethod'] == null ? undefined : json['shippingMethod'],
        'lineItemCount': json['lineItemCount'] == null ? undefined : json['lineItemCount'],
    };
}

export function OrderContextToJSON(json: any): OrderContext {
    return OrderContextToJSONTyped(json, false);
}

export function OrderContextToJSONTyped(value?: OrderContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'orderTotal': value['orderTotal'],
        'shippingMethod': value['shippingMethod'],
        'lineItemCount': value['lineItemCount'],
    };
}

