/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of payer (consumer or business).
 * @export
 * @enum {string}
 */
export enum PayerTypeEnum {
    Consumer = 'consumer',
    Business = 'business'
}


export function instanceOfPayerTypeEnum(value: any): boolean {
    for (const key in PayerTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PayerTypeEnum, key)) {
            if (PayerTypeEnum[key as keyof typeof PayerTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PayerTypeEnumFromJSON(json: any): PayerTypeEnum {
    return PayerTypeEnumFromJSONTyped(json, false);
}

export function PayerTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayerTypeEnum {
    return json as PayerTypeEnum;
}

export function PayerTypeEnumToJSON(value?: PayerTypeEnum | null): any {
    return value as any;
}

export function PayerTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PayerTypeEnum {
    return value as PayerTypeEnum;
}

