/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Refund outcome details.
 * @export
 * @interface PaymentRefundOutcome
 */
export interface PaymentRefundOutcome {
    /**
     * Refund status.
     * @type {string}
     * @memberof PaymentRefundOutcome
     */
    status?: PaymentRefundOutcomeStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum PaymentRefundOutcomeStatusEnum {
    None = 'none',
    Partial = 'partial',
    Full = 'full'
}


/**
 * Check if a given object implements the PaymentRefundOutcome interface.
 */
export function instanceOfPaymentRefundOutcome(value: object): value is PaymentRefundOutcome {
    return true;
}

export function PaymentRefundOutcomeFromJSON(json: any): PaymentRefundOutcome {
    return PaymentRefundOutcomeFromJSONTyped(json, false);
}

export function PaymentRefundOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRefundOutcome {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PaymentRefundOutcomeToJSON(json: any): PaymentRefundOutcome {
    return PaymentRefundOutcomeToJSONTyped(json, false);
}

export function PaymentRefundOutcomeToJSONTyped(value?: PaymentRefundOutcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

