/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authorization outcome details.
 * @export
 * @interface PaymentAuthorizationOutcome
 */
export interface PaymentAuthorizationOutcome {
    /**
     * Indicates whether authorization was approved.
     * @type {boolean}
     * @memberof PaymentAuthorizationOutcome
     */
    approved?: boolean;
    /**
     * Authorization response code.
     * @type {string}
     * @memberof PaymentAuthorizationOutcome
     */
    responseCode?: string;
}

/**
 * Check if a given object implements the PaymentAuthorizationOutcome interface.
 */
export function instanceOfPaymentAuthorizationOutcome(value: object): value is PaymentAuthorizationOutcome {
    return true;
}

export function PaymentAuthorizationOutcomeFromJSON(json: any): PaymentAuthorizationOutcome {
    return PaymentAuthorizationOutcomeFromJSONTyped(json, false);
}

export function PaymentAuthorizationOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentAuthorizationOutcome {
    if (json == null) {
        return json;
    }
    return {
        
        'approved': json['approved'] == null ? undefined : json['approved'],
        'responseCode': json['responseCode'] == null ? undefined : json['responseCode'],
    };
}

export function PaymentAuthorizationOutcomeToJSON(json: any): PaymentAuthorizationOutcome {
    return PaymentAuthorizationOutcomeToJSONTyped(json, false);
}

export function PaymentAuthorizationOutcomeToJSONTyped(value?: PaymentAuthorizationOutcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approved': value['approved'],
        'responseCode': value['responseCode'],
    };
}

