/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of real-time payment network used.
 * @export
 * @enum {string}
 */
export enum PaymentRealtimeTypeEnum {
    Zelle = 'zelle',
    Rtp = 'rtp',
    FedNow = 'fed_now',
    FasterPayments = 'faster_payments',
    Upi = 'upi'
}


export function instanceOfPaymentRealtimeTypeEnum(value: any): boolean {
    for (const key in PaymentRealtimeTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PaymentRealtimeTypeEnum, key)) {
            if (PaymentRealtimeTypeEnum[key as keyof typeof PaymentRealtimeTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentRealtimeTypeEnumFromJSON(json: any): PaymentRealtimeTypeEnum {
    return PaymentRealtimeTypeEnumFromJSONTyped(json, false);
}

export function PaymentRealtimeTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRealtimeTypeEnum {
    return json as PaymentRealtimeTypeEnum;
}

export function PaymentRealtimeTypeEnumToJSON(value?: PaymentRealtimeTypeEnum | null): any {
    return value as any;
}

export function PaymentRealtimeTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentRealtimeTypeEnum {
    return value as PaymentRealtimeTypeEnum;
}
