/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Common base for all payment method variants; determined by `type`.
 * @export
 * @interface PaymentMethodBase
 */
export interface PaymentMethodBase {
    /**
     * The payment instrument type for this purchase.
     * @type {string}
     * @memberof PaymentMethodBase
     */
    type: PaymentMethodBaseTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum PaymentMethodBaseTypeEnum {
    Card = 'card',
    Wallet = 'wallet',
    Realtime = 'realtime',
    BankTransfer = 'bank_transfer',
    Crypto = 'crypto',
    Invoice = 'invoice'
}


/**
 * Check if a given object implements the PaymentMethodBase interface.
 */
export function instanceOfPaymentMethodBase(value: object): value is PaymentMethodBase {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PaymentMethodBaseFromJSON(json: any): PaymentMethodBase {
    return PaymentMethodBaseFromJSONTyped(json, false);
}

export function PaymentMethodBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodBase {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function PaymentMethodBaseToJSON(json: any): PaymentMethodBase {
    return PaymentMethodBaseToJSONTyped(json, false);
}

export function PaymentMethodBaseToJSONTyped(value?: PaymentMethodBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}
