/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Chargeback details, including reason code.
 * @export
 * @interface PaymentChargeback
 */
export interface PaymentChargeback {
    /**
     * Chargeback reason code.
     * @type {string}
     * @memberof PaymentChargeback
     */
    reason?: string;
}

/**
 * Check if a given object implements the PaymentChargeback interface.
 */
export function instanceOfPaymentChargeback(value: object): value is PaymentChargeback {
    return true;
}

export function PaymentChargebackFromJSON(json: any): PaymentChargeback {
    return PaymentChargebackFromJSONTyped(json, false);
}

export function PaymentChargebackFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentChargeback {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function PaymentChargebackToJSON(json: any): PaymentChargeback {
    return PaymentChargebackToJSONTyped(json, false);
}

export function PaymentChargebackToJSONTyped(value?: PaymentChargeback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}
