/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Chargeback details, including reason code.
 * @export
 * @interface PaymentChargeback
 */
export interface PaymentChargeback {
    /**
     * Chargeback reason code.
     * @type {string}
     * @memberof PaymentChargeback
     */
    reason?: string;
}

/**
 * Check if a given object implements the PaymentChargeback interface.
 */
export function instanceOfPaymentChargeback(value: object): value is PaymentChargeback {
    return true;
}

export function PaymentChargebackFromJSON(json: any): PaymentChargeback {
    return PaymentChargebackFromJSONTyped(json, false);
}

export function PaymentChargebackFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentChargeback {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function PaymentChargebackToJSON(json: any): PaymentChargeback {
    return PaymentChargebackToJSONTyped(json, false);
}

export function PaymentChargebackToJSONTyped(value?: PaymentChargeback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

