/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of card used for the payment.
 * @export
 * @enum {string}
 */
export enum PaymentCardTypeEnum {
    Credit = 'credit',
    Debit = 'debit',
    Prepaid = 'prepaid'
}


export function instanceOfPaymentCardTypeEnum(value: any): boolean {
    for (const key in PaymentCardTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PaymentCardTypeEnum, key)) {
            if (PaymentCardTypeEnum[key as keyof typeof PaymentCardTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentCardTypeEnumFromJSON(json: any): PaymentCardTypeEnum {
    return PaymentCardTypeEnumFromJSONTyped(json, false);
}

export function PaymentCardTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCardTypeEnum {
    return json as PaymentCardTypeEnum;
}

export function PaymentCardTypeEnumToJSON(value?: PaymentCardTypeEnum | null): any {
    return value as any;
}

export function PaymentCardTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentCardTypeEnum {
    return value as PaymentCardTypeEnum;
}

