/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentCaptureOutcome } from './PaymentCaptureOutcome';
import {
    PaymentCaptureOutcomeFromJSON,
    PaymentCaptureOutcomeFromJSONTyped,
    PaymentCaptureOutcomeToJSON,
    PaymentCaptureOutcomeToJSONTyped,
} from './PaymentCaptureOutcome';
import type { PaymentChargeback } from './PaymentChargeback';
import {
    PaymentChargebackFromJSON,
    PaymentChargebackFromJSONTyped,
    PaymentChargebackToJSON,
    PaymentChargebackToJSONTyped,
} from './PaymentChargeback';
import type { PaymentDisputeOutcome } from './PaymentDisputeOutcome';
import {
    PaymentDisputeOutcomeFromJSON,
    PaymentDisputeOutcomeFromJSONTyped,
    PaymentDisputeOutcomeToJSON,
    PaymentDisputeOutcomeToJSONTyped,
} from './PaymentDisputeOutcome';
import type { PaymentRefundOutcome } from './PaymentRefundOutcome';
import {
    PaymentRefundOutcomeFromJSON,
    PaymentRefundOutcomeFromJSONTyped,
    PaymentRefundOutcomeToJSON,
    PaymentRefundOutcomeToJSONTyped,
} from './PaymentRefundOutcome';
import type { PaymentAuthorizationOutcome } from './PaymentAuthorizationOutcome';
import {
    PaymentAuthorizationOutcomeFromJSON,
    PaymentAuthorizationOutcomeFromJSONTyped,
    PaymentAuthorizationOutcomeToJSON,
    PaymentAuthorizationOutcomeToJSONTyped,
} from './PaymentAuthorizationOutcome';
import type { PaymentChargebackOutcome } from './PaymentChargebackOutcome';
import {
    PaymentChargebackOutcomeFromJSON,
    PaymentChargebackOutcomeFromJSONTyped,
    PaymentChargebackOutcomeToJSON,
    PaymentChargebackOutcomeToJSONTyped,
} from './PaymentChargebackOutcome';

/**
 * Payment outcome details. Structured by lifecycle stage for clarity and validation. Stages include authorization, capture, refund, dispute, chargeback, and chargebackOutcome.
 * 
 * @export
 * @interface PaymentOutcome
 */
export interface PaymentOutcome {
    /**
     * 
     * @type {PaymentAuthorizationOutcome}
     * @memberof PaymentOutcome
     */
    authorization?: PaymentAuthorizationOutcome;
    /**
     * 
     * @type {PaymentCaptureOutcome}
     * @memberof PaymentOutcome
     */
    capture?: PaymentCaptureOutcome;
    /**
     * 
     * @type {PaymentRefundOutcome}
     * @memberof PaymentOutcome
     */
    refund?: PaymentRefundOutcome;
    /**
     * 
     * @type {PaymentDisputeOutcome}
     * @memberof PaymentOutcome
     */
    dispute?: PaymentDisputeOutcome;
    /**
     * 
     * @type {PaymentChargeback}
     * @memberof PaymentOutcome
     */
    chargeback?: PaymentChargeback;
    /**
     * 
     * @type {PaymentChargebackOutcome}
     * @memberof PaymentOutcome
     */
    chargebackOutcome?: PaymentChargebackOutcome;
}

/**
 * Check if a given object implements the PaymentOutcome interface.
 */
export function instanceOfPaymentOutcome(value: object): value is PaymentOutcome {
    return true;
}

export function PaymentOutcomeFromJSON(json: any): PaymentOutcome {
    return PaymentOutcomeFromJSONTyped(json, false);
}

export function PaymentOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentOutcome {
    if (json == null) {
        return json;
    }
    return {
        
        'authorization': json['authorization'] == null ? undefined : PaymentAuthorizationOutcomeFromJSON(json['authorization']),
        'capture': json['capture'] == null ? undefined : PaymentCaptureOutcomeFromJSON(json['capture']),
        'refund': json['refund'] == null ? undefined : PaymentRefundOutcomeFromJSON(json['refund']),
        'dispute': json['dispute'] == null ? undefined : PaymentDisputeOutcomeFromJSON(json['dispute']),
        'chargeback': json['chargeback'] == null ? undefined : PaymentChargebackFromJSON(json['chargeback']),
        'chargebackOutcome': json['chargebackOutcome'] == null ? undefined : PaymentChargebackOutcomeFromJSON(json['chargebackOutcome']),
    };
}

export function PaymentOutcomeToJSON(json: any): PaymentOutcome {
    return PaymentOutcomeToJSONTyped(json, false);
}

export function PaymentOutcomeToJSONTyped(value?: PaymentOutcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorization': PaymentAuthorizationOutcomeToJSON(value['authorization']),
        'capture': PaymentCaptureOutcomeToJSON(value['capture']),
        'refund': PaymentRefundOutcomeToJSON(value['refund']),
        'dispute': PaymentDisputeOutcomeToJSON(value['dispute']),
        'chargeback': PaymentChargebackToJSON(value['chargeback']),
        'chargebackOutcome': PaymentChargebackOutcomeToJSON(value['chargebackOutcome']),
    };
}

