/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of payment lifecycle event.
 * @export
 * @enum {string}
 */
export enum PaymentEventType {
    Authorization = 'authorization',
    Capture = 'capture',
    Settlement = 'settlement',
    Refund = 'refund',
    Dispute = 'dispute',
    Chargeback = 'chargeback',
    ChargebackOutcome = 'chargeback_outcome'
}


export function instanceOfPaymentEventType(value: any): boolean {
    for (const key in PaymentEventType) {
        if (Object.prototype.hasOwnProperty.call(PaymentEventType, key)) {
            if (PaymentEventType[key as keyof typeof PaymentEventType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentEventTypeFromJSON(json: any): PaymentEventType {
    return PaymentEventTypeFromJSONTyped(json, false);
}

export function PaymentEventTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentEventType {
    return json as PaymentEventType;
}

export function PaymentEventTypeToJSON(value?: PaymentEventType | null): any {
    return value as any;
}

export function PaymentEventTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentEventType {
    return value as PaymentEventType;
}

