/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Capture outcome details.
 * @export
 * @interface PaymentCaptureOutcome
 */
export interface PaymentCaptureOutcome {
    /**
     * Capture status.
     * @type {string}
     * @memberof PaymentCaptureOutcome
     */
    status?: PaymentCaptureOutcomeStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum PaymentCaptureOutcomeStatusEnum {
    None = 'none',
    Partial = 'partial',
    Full = 'full',
    Failed = 'failed'
}


/**
 * Check if a given object implements the PaymentCaptureOutcome interface.
 */
export function instanceOfPaymentCaptureOutcome(value: object): value is PaymentCaptureOutcome {
    return true;
}

export function PaymentCaptureOutcomeFromJSON(json: any): PaymentCaptureOutcome {
    return PaymentCaptureOutcomeFromJSONTyped(json, false);
}

export function PaymentCaptureOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCaptureOutcome {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PaymentCaptureOutcomeToJSON(json: any): PaymentCaptureOutcome {
    return PaymentCaptureOutcomeToJSONTyped(json, false);
}

export function PaymentCaptureOutcomeToJSONTyped(value?: PaymentCaptureOutcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}
