/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dispute lifecycle status for the transaction.
 * @export
 * @interface PaymentDisputeOutcome
 */
export interface PaymentDisputeOutcome {
    /**
     * Dispute status.
     * @type {string}
     * @memberof PaymentDisputeOutcome
     */
    status?: PaymentDisputeOutcomeStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum PaymentDisputeOutcomeStatusEnum {
    None = 'none',
    Open = 'open',
    Won = 'won',
    Lost = 'lost',
    Canceled = 'canceled'
}


/**
 * Check if a given object implements the PaymentDisputeOutcome interface.
 */
export function instanceOfPaymentDisputeOutcome(value: object): value is PaymentDisputeOutcome {
    return true;
}

export function PaymentDisputeOutcomeFromJSON(json: any): PaymentDisputeOutcome {
    return PaymentDisputeOutcomeFromJSONTyped(json, false);
}

export function PaymentDisputeOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentDisputeOutcome {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PaymentDisputeOutcomeToJSON(json: any): PaymentDisputeOutcome {
    return PaymentDisputeOutcomeToJSONTyped(json, false);
}

export function PaymentDisputeOutcomeToJSONTyped(value?: PaymentDisputeOutcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

