/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Final disposition of the chargeback after investigation/representment.
 * @export
 * @interface PaymentChargebackOutcome
 */
export interface PaymentChargebackOutcome {
    /**
     * Outcome of the chargeback case.
     * @type {string}
     * @memberof PaymentChargebackOutcome
     */
    status?: PaymentChargebackOutcomeStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum PaymentChargebackOutcomeStatusEnum {
    Won = 'won',
    Lost = 'lost',
    Representment = 'representment',
    Reversed = 'reversed'
}


/**
 * Check if a given object implements the PaymentChargebackOutcome interface.
 */
export function instanceOfPaymentChargebackOutcome(value: object): value is PaymentChargebackOutcome {
    return true;
}

export function PaymentChargebackOutcomeFromJSON(json: any): PaymentChargebackOutcome {
    return PaymentChargebackOutcomeFromJSONTyped(json, false);
}

export function PaymentChargebackOutcomeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentChargebackOutcome {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function PaymentChargebackOutcomeToJSON(json: any): PaymentChargebackOutcome {
    return PaymentChargebackOutcomeToJSONTyped(json, false);
}

export function PaymentChargebackOutcomeToJSONTyped(value?: PaymentChargebackOutcome | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

