/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of digital wallet used for the payment.
 * @export
 * @enum {string}
 */
export enum PaymentWalletTypeEnum {
    Paypal = 'paypal',
    ApplePay = 'apple_pay',
    GooglePay = 'google_pay',
    CashApp = 'cash_app',
    Venmo = 'venmo'
}


export function instanceOfPaymentWalletTypeEnum(value: any): boolean {
    for (const key in PaymentWalletTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PaymentWalletTypeEnum, key)) {
            if (PaymentWalletTypeEnum[key as keyof typeof PaymentWalletTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentWalletTypeEnumFromJSON(json: any): PaymentWalletTypeEnum {
    return PaymentWalletTypeEnumFromJSONTyped(json, false);
}

export function PaymentWalletTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentWalletTypeEnum {
    return json as PaymentWalletTypeEnum;
}

export function PaymentWalletTypeEnumToJSON(value?: PaymentWalletTypeEnum | null): any {
    return value as any;
}

export function PaymentWalletTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentWalletTypeEnum {
    return value as PaymentWalletTypeEnum;
}

