/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentEventType } from './PaymentEventType';
import {
    PaymentEventTypeFromJSON,
    PaymentEventTypeFromJSONTyped,
    PaymentEventTypeToJSON,
    PaymentEventTypeToJSONTyped,
} from './PaymentEventType';
import type { PaymentOutcome } from './PaymentOutcome';
import {
    PaymentOutcomeFromJSON,
    PaymentOutcomeFromJSONTyped,
    PaymentOutcomeToJSON,
    PaymentOutcomeToJSONTyped,
} from './PaymentOutcome';

/**
 * Payment lifecycle event.
 * @export
 * @interface PaymentEvent
 */
export interface PaymentEvent {
    /**
     * Server-minted unique payment identifier.
     * @type {string}
     * @memberof PaymentEvent
     */
    paymentIntentId: string;
    /**
     * 
     * @type {PaymentEventType}
     * @memberof PaymentEvent
     */
    eventType: PaymentEventType;
    /**
     * RFC 3339 timestamp with timezone.
     * @type {string}
     * @memberof PaymentEvent
     */
    timestamp: string;
    /**
     * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.
     * 
     * @type {number}
     * @memberof PaymentEvent
     */
    amount?: number;
    /**
     * ISO 4217 currency code (e.g., 'USD').
     * @type {string}
     * @memberof PaymentEvent
     */
    currency?: string;
    /**
     * 
     * @type {PaymentOutcome}
     * @memberof PaymentEvent
     */
    outcome?: PaymentOutcome;
    /**
     * Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.
     * 
     * @type {string}
     * @memberof PaymentEvent
     */
    metadata?: string;
}



/**
 * Check if a given object implements the PaymentEvent interface.
 */
export function instanceOfPaymentEvent(value: object): value is PaymentEvent {
    if (!('paymentIntentId' in value) || value['paymentIntentId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PaymentEventFromJSON(json: any): PaymentEvent {
    return PaymentEventFromJSONTyped(json, false);
}

export function PaymentEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentIntentId': json['paymentIntentId'],
        'eventType': PaymentEventTypeFromJSON(json['eventType']),
        'timestamp': json['timestamp'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'outcome': json['outcome'] == null ? undefined : PaymentOutcomeFromJSON(json['outcome']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function PaymentEventToJSON(json: any): PaymentEvent {
    return PaymentEventToJSONTyped(json, false);
}

export function PaymentEventToJSONTyped(value?: PaymentEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentIntentId': value['paymentIntentId'],
        'eventType': PaymentEventTypeToJSON(value['eventType']),
        'timestamp': value['timestamp'],
        'amount': value['amount'],
        'currency': value['currency'],
        'outcome': PaymentOutcomeToJSON(value['outcome']),
        'metadata': value['metadata'],
    };
}

