/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of digital wallet used for the payment.
 * @export
 * @enum {string}
 */
export enum PaymentWalletTypeEnum {
    Paypal = 'paypal',
    ApplePay = 'apple_pay',
    GooglePay = 'google_pay',
    CashApp = 'cash_app',
    Venmo = 'venmo'
}


export function instanceOfPaymentWalletTypeEnum(value: any): boolean {
    for (const key in PaymentWalletTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PaymentWalletTypeEnum, key)) {
            if (PaymentWalletTypeEnum[key as keyof typeof PaymentWalletTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentWalletTypeEnumFromJSON(json: any): PaymentWalletTypeEnum {
    return PaymentWalletTypeEnumFromJSONTyped(json, false);
}

export function PaymentWalletTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentWalletTypeEnum {
    return json as PaymentWalletTypeEnum;
}

export function PaymentWalletTypeEnumToJSON(value?: PaymentWalletTypeEnum | null): any {
    return value as any;
}

export function PaymentWalletTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentWalletTypeEnum {
    return value as PaymentWalletTypeEnum;
}

