/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BankTransfer } from './BankTransfer';
import {
    instanceOfBankTransfer,
    BankTransferFromJSON,
    BankTransferFromJSONTyped,
    BankTransferToJSON,
} from './BankTransfer';
import type { Card } from './Card';
import {
    instanceOfCard,
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
} from './Card';
import type { Crypto } from './Crypto';
import {
    instanceOfCrypto,
    CryptoFromJSON,
    CryptoFromJSONTyped,
    CryptoToJSON,
} from './Crypto';
import type { Invoice } from './Invoice';
import {
    instanceOfInvoice,
    InvoiceFromJSON,
    InvoiceFromJSONTyped,
    InvoiceToJSON,
} from './Invoice';
import type { Realtime } from './Realtime';
import {
    instanceOfRealtime,
    RealtimeFromJSON,
    RealtimeFromJSONTyped,
    RealtimeToJSON,
} from './Realtime';
import type { Wallet } from './Wallet';
import {
    instanceOfWallet,
    WalletFromJSON,
    WalletFromJSONTyped,
    WalletToJSON,
} from './Wallet';

/**
 * @type PaymentMethod
 * Union of instrument-specific payment details.
 * @export
 */
export type PaymentMethod = { type: 'bank_transfer' } & BankTransfer | { type: 'card' } & Card | { type: 'crypto' } & Crypto | { type: 'invoice' } & Invoice | { type: 'realtime' } & Realtime | { type: 'wallet' } & Wallet;

export function PaymentMethodFromJSON(json: any): PaymentMethod {
    return PaymentMethodFromJSONTyped(json, false);
}

export function PaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethod {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'bank_transfer':
            return Object.assign({}, BankTransferFromJSONTyped(json, true), { type: 'bank_transfer' } as const);
        case 'card':
            return Object.assign({}, CardFromJSONTyped(json, true), { type: 'card' } as const);
        case 'crypto':
            return Object.assign({}, CryptoFromJSONTyped(json, true), { type: 'crypto' } as const);
        case 'invoice':
            return Object.assign({}, InvoiceFromJSONTyped(json, true), { type: 'invoice' } as const);
        case 'realtime':
            return Object.assign({}, RealtimeFromJSONTyped(json, true), { type: 'realtime' } as const);
        case 'wallet':
            return Object.assign({}, WalletFromJSONTyped(json, true), { type: 'wallet' } as const);
        default:
            return json;
    }
}

export function PaymentMethodToJSON(json: any): any {
    return PaymentMethodToJSONTyped(json, false);
}

export function PaymentMethodToJSONTyped(value?: PaymentMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'bank_transfer':
            return Object.assign({}, BankTransferToJSON(value), { type: 'bank_transfer' } as const);
        case 'card':
            return Object.assign({}, CardToJSON(value), { type: 'card' } as const);
        case 'crypto':
            return Object.assign({}, CryptoToJSON(value), { type: 'crypto' } as const);
        case 'invoice':
            return Object.assign({}, InvoiceToJSON(value), { type: 'invoice' } as const);
        case 'realtime':
            return Object.assign({}, RealtimeToJSON(value), { type: 'realtime' } as const);
        case 'wallet':
            return Object.assign({}, WalletToJSON(value), { type: 'wallet' } as const);
        default:
            return value;
    }
}

