/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of real-time payment network used.
 * @export
 * @enum {string}
 */
export enum PaymentRealtimeTypeEnum {
    Zelle = 'zelle',
    Rtp = 'rtp',
    FedNow = 'fed_now',
    FasterPayments = 'faster_payments',
    Upi = 'upi'
}


export function instanceOfPaymentRealtimeTypeEnum(value: any): boolean {
    for (const key in PaymentRealtimeTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PaymentRealtimeTypeEnum, key)) {
            if (PaymentRealtimeTypeEnum[key as keyof typeof PaymentRealtimeTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentRealtimeTypeEnumFromJSON(json: any): PaymentRealtimeTypeEnum {
    return PaymentRealtimeTypeEnumFromJSONTyped(json, false);
}

export function PaymentRealtimeTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRealtimeTypeEnum {
    return json as PaymentRealtimeTypeEnum;
}

export function PaymentRealtimeTypeEnumToJSON(value?: PaymentRealtimeTypeEnum | null): any {
    return value as any;
}

export function PaymentRealtimeTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentRealtimeTypeEnum {
    return value as PaymentRealtimeTypeEnum;
}

