/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Postal address used for shipping or billing. Raw values are used only
 * for normalization and risk signals; Alogram will not persist raw address
 * fields in long-term storage.
 * 
 * @export
 * @interface PostalAddress
 */
export interface PostalAddress {
    /**
     * First line of the street address.
     * @type {string}
     * @memberof PostalAddress
     */
    line1?: string;
    /**
     * Second line of the street address (apartment, suite, etc.).
     * @type {string}
     * @memberof PostalAddress
     */
    line2?: string;
    /**
     * City or locality.
     * @type {string}
     * @memberof PostalAddress
     */
    city?: string;
    /**
     * State, province, or region.
     * @type {string}
     * @memberof PostalAddress
     */
    region?: string;
    /**
     * Postal / ZIP code.
     * @type {string}
     * @memberof PostalAddress
     */
    postalCode?: string;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof PostalAddress
     */
    country?: string;
}

/**
 * Check if a given object implements the PostalAddress interface.
 */
export function instanceOfPostalAddress(value: object): value is PostalAddress {
    return true;
}

export function PostalAddressFromJSON(json: any): PostalAddress {
    return PostalAddressFromJSONTyped(json, false);
}

export function PostalAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostalAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'line1': json['line1'] == null ? undefined : json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'city': json['city'] == null ? undefined : json['city'],
        'region': json['region'] == null ? undefined : json['region'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function PostalAddressToJSON(json: any): PostalAddress {
    return PostalAddressToJSONTyped(json, false);
}

export function PostalAddressToJSONTyped(value?: PostalAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line1': value['line1'],
        'line2': value['line2'],
        'city': value['city'],
        'region': value['region'],
        'postalCode': value['postalCode'],
        'country': value['country'],
    };
}

