/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * RFC 7807 Problem Details
 * @export
 * @interface Problem
 */
export interface Problem {
    /**
     * A URI reference that identifies the problem type.
     * @type {string}
     * @memberof Problem
     */
    type?: string;
    /**
     * A short, human-readable summary of the problem type.
     * @type {string}
     * @memberof Problem
     */
    title: string;
    /**
     * The HTTP status code applicable to this problem.
     * @type {number}
     * @memberof Problem
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence.
     * @type {string}
     * @memberof Problem
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence.
     * @type {string}
     * @memberof Problem
     */
    instance?: string;
    /**
     * Application-specific error code.
     * @type {string}
     * @memberof Problem
     */
    errorCode?: string;
}

/**
 * Check if a given object implements the Problem interface.
 */
export function instanceOfProblem(value: object): value is Problem {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProblemFromJSON(json: any): Problem {
    return ProblemFromJSONTyped(json, false);
}

export function ProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Problem {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'],
        'status': json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'errorCode': json['errorCode'] == null ? undefined : json['errorCode'],
    };
}

export function ProblemToJSON(json: any): Problem {
    return ProblemToJSONTyped(json, false);
}

export function ProblemToJSONTyped(value?: Problem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'instance': value['instance'],
        'errorCode': value['errorCode'],
    };
}
