/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MerchantContext } from './MerchantContext';
import {
    MerchantContextFromJSON,
    MerchantContextFromJSONTyped,
    MerchantContextToJSON,
    MerchantContextToJSONTyped,
} from './MerchantContext';
import type { PayerTypeEnum } from './PayerTypeEnum';
import {
    PayerTypeEnumFromJSON,
    PayerTypeEnumFromJSONTyped,
    PayerTypeEnumToJSON,
    PayerTypeEnumToJSONTyped,
} from './PayerTypeEnum';
import type { EntryMethodEnum } from './EntryMethodEnum';
import {
    EntryMethodEnumFromJSON,
    EntryMethodEnumFromJSONTyped,
    EntryMethodEnumToJSON,
    EntryMethodEnumToJSONTyped,
} from './EntryMethodEnum';
import type { StoredCredentialContext } from './StoredCredentialContext';
import {
    StoredCredentialContextFromJSON,
    StoredCredentialContextFromJSONTyped,
    StoredCredentialContextToJSON,
    StoredCredentialContextToJSONTyped,
} from './StoredCredentialContext';
import type { DeviceInfo } from './DeviceInfo';
import {
    DeviceInfoFromJSON,
    DeviceInfoFromJSONTyped,
    DeviceInfoToJSON,
    DeviceInfoToJSONTyped,
} from './DeviceInfo';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';
import type { DiscountCode } from './DiscountCode';
import {
    DiscountCodeFromJSON,
    DiscountCodeFromJSONTyped,
    DiscountCodeToJSON,
    DiscountCodeToJSONTyped,
} from './DiscountCode';
import type { ChannelEnum } from './ChannelEnum';
import {
    ChannelEnumFromJSON,
    ChannelEnumFromJSONTyped,
    ChannelEnumToJSON,
    ChannelEnumToJSONTyped,
} from './ChannelEnum';
import type { OrderContext } from './OrderContext';
import {
    OrderContextFromJSON,
    OrderContextFromJSONTyped,
    OrderContextToJSON,
    OrderContextToJSONTyped,
} from './OrderContext';

/**
 * Purchase details for fraud checks; core fields are common, instrument specifics live in `paymentMethod`.
 * 
 * @export
 * @interface Purchase
 */
export interface Purchase {
    /**
     * Unique identifier for the location where the transaction occurred.
     * @type {string}
     * @memberof Purchase
     */
    locationId?: string;
    /**
     * 
     * @type {DeviceInfo}
     * @memberof Purchase
     */
    deviceInfo?: DeviceInfo;
    /**
     * RFC 3339 timestamp with timezone.
     * @type {string}
     * @memberof Purchase
     */
    timestamp?: string;
    /**
     * A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens.
     * 
     * @type {string}
     * @memberof Purchase
     */
    transactionId?: string;
    /**
     * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.
     * 
     * @type {number}
     * @memberof Purchase
     */
    amount: number;
    /**
     * ISO 4217 currency code (e.g., 'USD').
     * @type {string}
     * @memberof Purchase
     */
    currency: string;
    /**
     * 
     * @type {ChannelEnum}
     * @memberof Purchase
     */
    channel?: ChannelEnum;
    /**
     * 
     * @type {EntryMethodEnum}
     * @memberof Purchase
     */
    entryMethod?: EntryMethodEnum;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof Purchase
     */
    paymentMethod: PaymentMethod;
    /**
     * 
     * @type {OrderContext}
     * @memberof Purchase
     */
    order?: OrderContext;
    /**
     * List of discount codes applied to the purchase.
     * @type {Array<DiscountCode>}
     * @memberof Purchase
     */
    discounts?: Array<DiscountCode>;
    /**
     * 
     * @type {PayerTypeEnum}
     * @memberof Purchase
     */
    payerType?: PayerTypeEnum;
    /**
     * 
     * @type {StoredCredentialContext}
     * @memberof Purchase
     */
    storedCredential?: StoredCredentialContext;
    /**
     * 
     * @type {MerchantContext}
     * @memberof Purchase
     */
    merchant?: MerchantContext;
    /**
     * Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.
     * 
     * @type {string}
     * @memberof Purchase
     */
    metadata?: string;
}



/**
 * Check if a given object implements the Purchase interface.
 */
export function instanceOfPurchase(value: object): value is Purchase {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function PurchaseFromJSON(json: any): Purchase {
    return PurchaseFromJSONTyped(json, false);
}

export function PurchaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Purchase {
    if (json == null) {
        return json;
    }
    return {
        
        'locationId': json['locationId'] == null ? undefined : json['locationId'],
        'deviceInfo': json['deviceInfo'] == null ? undefined : DeviceInfoFromJSON(json['deviceInfo']),
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'channel': json['channel'] == null ? undefined : ChannelEnumFromJSON(json['channel']),
        'entryMethod': json['entryMethod'] == null ? undefined : EntryMethodEnumFromJSON(json['entryMethod']),
        'paymentMethod': PaymentMethodFromJSON(json['paymentMethod']),
        'order': json['order'] == null ? undefined : OrderContextFromJSON(json['order']),
        'discounts': json['discounts'] == null ? undefined : ((json['discounts'] as Array<any>).map(DiscountCodeFromJSON)),
        'payerType': json['payerType'] == null ? undefined : PayerTypeEnumFromJSON(json['payerType']),
        'storedCredential': json['storedCredential'] == null ? undefined : StoredCredentialContextFromJSON(json['storedCredential']),
        'merchant': json['merchant'] == null ? undefined : MerchantContextFromJSON(json['merchant']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function PurchaseToJSON(json: any): Purchase {
    return PurchaseToJSONTyped(json, false);
}

export function PurchaseToJSONTyped(value?: Purchase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationId': value['locationId'],
        'deviceInfo': DeviceInfoToJSON(value['deviceInfo']),
        'timestamp': value['timestamp'],
        'transactionId': value['transactionId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'channel': ChannelEnumToJSON(value['channel']),
        'entryMethod': EntryMethodEnumToJSON(value['entryMethod']),
        'paymentMethod': PaymentMethodToJSON(value['paymentMethod']),
        'order': OrderContextToJSON(value['order']),
        'discounts': value['discounts'] == null ? undefined : ((value['discounts'] as Array<any>).map(DiscountCodeToJSON)),
        'payerType': PayerTypeEnumToJSON(value['payerType']),
        'storedCredential': StoredCredentialContextToJSON(value['storedCredential']),
        'merchant': MerchantContextToJSON(value['merchant']),
        'metadata': value['metadata'],
    };
}

