/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * First transaction in the series vs a subsequent one.
 * @export
 * @enum {string}
 */
export enum PurchaseSequenceEnum {
    First = 'first',
    Subsequent = 'subsequent'
}


export function instanceOfPurchaseSequenceEnum(value: any): boolean {
    for (const key in PurchaseSequenceEnum) {
        if (Object.prototype.hasOwnProperty.call(PurchaseSequenceEnum, key)) {
            if (PurchaseSequenceEnum[key as keyof typeof PurchaseSequenceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PurchaseSequenceEnumFromJSON(json: any): PurchaseSequenceEnum {
    return PurchaseSequenceEnumFromJSONTyped(json, false);
}

export function PurchaseSequenceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseSequenceEnum {
    return json as PurchaseSequenceEnum;
}

export function PurchaseSequenceEnumToJSON(value?: PurchaseSequenceEnum | null): any {
    return value as any;
}

export function PurchaseSequenceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PurchaseSequenceEnum {
    return value as PurchaseSequenceEnum;
}

