/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Who initiated the transaction (CIT vs MIT).
 * @export
 * @enum {string}
 */
export enum PurchaseInitiatorEnum {
    Cardholder = 'cardholder',
    Merchant = 'merchant'
}


export function instanceOfPurchaseInitiatorEnum(value: any): boolean {
    for (const key in PurchaseInitiatorEnum) {
        if (Object.prototype.hasOwnProperty.call(PurchaseInitiatorEnum, key)) {
            if (PurchaseInitiatorEnum[key as keyof typeof PurchaseInitiatorEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PurchaseInitiatorEnumFromJSON(json: any): PurchaseInitiatorEnum {
    return PurchaseInitiatorEnumFromJSONTyped(json, false);
}

export function PurchaseInitiatorEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseInitiatorEnum {
    return json as PurchaseInitiatorEnum;
}

export function PurchaseInitiatorEnumToJSON(value?: PurchaseInitiatorEnum | null): any {
    return value as any;
}

export function PurchaseInitiatorEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PurchaseInitiatorEnum {
    return value as PurchaseInitiatorEnum;
}

