/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payment use case.
 * @export
 * @enum {string}
 */
export enum PurchaseUsageEnum {
    OneTime = 'one_time',
    Recurring = 'recurring',
    Installment = 'installment',
    Unscheduled = 'unscheduled'
}


export function instanceOfPurchaseUsageEnum(value: any): boolean {
    for (const key in PurchaseUsageEnum) {
        if (Object.prototype.hasOwnProperty.call(PurchaseUsageEnum, key)) {
            if (PurchaseUsageEnum[key as keyof typeof PurchaseUsageEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PurchaseUsageEnumFromJSON(json: any): PurchaseUsageEnum {
    return PurchaseUsageEnumFromJSONTyped(json, false);
}

export function PurchaseUsageEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseUsageEnum {
    return json as PurchaseUsageEnum;
}

export function PurchaseUsageEnumToJSON(value?: PurchaseUsageEnum | null): any {
    return value as any;
}

export function PurchaseUsageEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PurchaseUsageEnum {
    return value as PurchaseUsageEnum;
}
