/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentRealtimeTypeEnum } from './PaymentRealtimeTypeEnum';
import {
    PaymentRealtimeTypeEnumFromJSON,
    PaymentRealtimeTypeEnumFromJSONTyped,
    PaymentRealtimeTypeEnumToJSON,
    PaymentRealtimeTypeEnumToJSONTyped,
} from './PaymentRealtimeTypeEnum';

/**
 * Real-time account-to-account rails (e.g., Zelle, RTP, FedNow, Faster Payments, UPI).
 * @export
 * @interface Realtime
 */
export interface Realtime {
    /**
     * Fixed to `realtime` for this schema.
     * @type {string}
     * @memberof Realtime
     */
    type: RealtimeTypeEnum;
    /**
     * 
     * @type {PaymentRealtimeTypeEnum}
     * @memberof Realtime
     */
    realtimeType?: PaymentRealtimeTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum RealtimeTypeEnum {
    Realtime = 'realtime'
}


/**
 * Check if a given object implements the Realtime interface.
 */
export function instanceOfRealtime(value: object): value is Realtime {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RealtimeFromJSON(json: any): Realtime {
    return RealtimeFromJSONTyped(json, false);
}

export function RealtimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Realtime {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'realtimeType': json['realtimeType'] == null ? undefined : PaymentRealtimeTypeEnumFromJSON(json['realtimeType']),
    };
}

export function RealtimeToJSON(json: any): Realtime {
    return RealtimeToJSONTyped(json, false);
}

export function RealtimeToJSONTyped(value?: Realtime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'realtimeType': PaymentRealtimeTypeEnumToJSON(value['realtimeType']),
    };
}

