/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentRealtimeTypeEnum } from './PaymentRealtimeTypeEnum';
import {
    PaymentRealtimeTypeEnumFromJSON,
    PaymentRealtimeTypeEnumFromJSONTyped,
    PaymentRealtimeTypeEnumToJSON,
    PaymentRealtimeTypeEnumToJSONTyped,
} from './PaymentRealtimeTypeEnum';

/**
 * Real-time account-to-account rails (e.g., Zelle, RTP, FedNow, Faster Payments, UPI).
 * @export
 * @interface Realtime
 */
export interface Realtime {
    /**
     * Fixed to `realtime` for this schema.
     * @type {string}
     * @memberof Realtime
     */
    type: RealtimeTypeEnum;
    /**
     * 
     * @type {PaymentRealtimeTypeEnum}
     * @memberof Realtime
     */
    realtimeType?: PaymentRealtimeTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum RealtimeTypeEnum {
    Realtime = 'realtime'
}


/**
 * Check if a given object implements the Realtime interface.
 */
export function instanceOfRealtime(value: object): value is Realtime {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RealtimeFromJSON(json: any): Realtime {
    return RealtimeFromJSONTyped(json, false);
}

export function RealtimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Realtime {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'realtimeType': json['realtimeType'] == null ? undefined : PaymentRealtimeTypeEnumFromJSON(json['realtimeType']),
    };
}

export function RealtimeToJSON(json: any): Realtime {
    return RealtimeToJSONTyped(json, false);
}

export function RealtimeToJSONTyped(value?: Realtime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'realtimeType': PaymentRealtimeTypeEnumToJSON(value['realtimeType']),
    };
}

