/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskCategoryEnum } from './RiskCategoryEnum';
import {
    RiskCategoryEnumFromJSON,
    RiskCategoryEnumFromJSONTyped,
    RiskCategoryEnumToJSON,
    RiskCategoryEnumToJSONTyped,
} from './RiskCategoryEnum';

/**
 * Merchant-friendly detail for a specific risk reason.
 * @export
 * @interface ReasonDetail
 */
export interface ReasonDetail {
    /**
     * Technical reason code (e.g., GEO_COUNTRY_SANCTIONED).
     * @type {string}
     * @memberof ReasonDetail
     */
    code: string;
    /**
     * 
     * @type {RiskCategoryEnum}
     * @memberof ReasonDetail
     */
    category: RiskCategoryEnum;
    /**
     * Merchant-friendly name for the risk reason.
     * @type {string}
     * @memberof ReasonDetail
     */
    displayName: string;
    /**
     * Detailed explanation of the risk signal.
     * @type {string}
     * @memberof ReasonDetail
     */
    description?: string;
    /**
     * Suggested action for the merchant to mitigate this specific risk.
     * @type {string}
     * @memberof ReasonDetail
     */
    recommendedAction?: string;
}



/**
 * Check if a given object implements the ReasonDetail interface.
 */
export function instanceOfReasonDetail(value: object): value is ReasonDetail {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function ReasonDetailFromJSON(json: any): ReasonDetail {
    return ReasonDetailFromJSONTyped(json, false);
}

export function ReasonDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasonDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'category': RiskCategoryEnumFromJSON(json['category']),
        'displayName': json['displayName'],
        'description': json['description'] == null ? undefined : json['description'],
        'recommendedAction': json['recommendedAction'] == null ? undefined : json['recommendedAction'],
    };
}

export function ReasonDetailToJSON(json: any): ReasonDetail {
    return ReasonDetailToJSONTyped(json, false);
}

export function ReasonDetailToJSONTyped(value?: ReasonDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'category': RiskCategoryEnumToJSON(value['category']),
        'displayName': value['displayName'],
        'description': value['description'],
        'recommendedAction': value['recommendedAction'],
    };
}

