/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RiskCategoryEnum } from './RiskCategoryEnum';
import {
    RiskCategoryEnumFromJSON,
    RiskCategoryEnumFromJSONTyped,
    RiskCategoryEnumToJSON,
    RiskCategoryEnumToJSONTyped,
} from './RiskCategoryEnum';

/**
 * Merchant-friendly detail for a specific risk reason.
 * @export
 * @interface ReasonDetail
 */
export interface ReasonDetail {
    /**
     * Technical reason code (e.g., GEO_COUNTRY_SANCTIONED).
     * @type {string}
     * @memberof ReasonDetail
     */
    code: string;
    /**
     * 
     * @type {RiskCategoryEnum}
     * @memberof ReasonDetail
     */
    category: RiskCategoryEnum;
    /**
     * Merchant-friendly name for the risk reason.
     * @type {string}
     * @memberof ReasonDetail
     */
    displayName: string;
    /**
     * Detailed explanation of the risk signal.
     * @type {string}
     * @memberof ReasonDetail
     */
    description?: string;
    /**
     * Suggested action for the merchant to mitigate this specific risk.
     * @type {string}
     * @memberof ReasonDetail
     */
    recommendedAction?: string;
}



/**
 * Check if a given object implements the ReasonDetail interface.
 */
export function instanceOfReasonDetail(value: object): value is ReasonDetail {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function ReasonDetailFromJSON(json: any): ReasonDetail {
    return ReasonDetailFromJSONTyped(json, false);
}

export function ReasonDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReasonDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'category': RiskCategoryEnumFromJSON(json['category']),
        'displayName': json['displayName'],
        'description': json['description'] == null ? undefined : json['description'],
        'recommendedAction': json['recommendedAction'] == null ? undefined : json['recommendedAction'],
    };
}

export function ReasonDetailToJSON(json: any): ReasonDetail {
    return ReasonDetailToJSONTyped(json, false);
}

export function ReasonDetailToJSONTyped(value?: ReasonDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'category': RiskCategoryEnumToJSON(value['category']),
        'displayName': value['displayName'],
        'description': value['description'],
        'recommendedAction': value['recommendedAction'],
    };
}

