/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * High-level business category for risk signals.
 * @export
 * @enum {string}
 */
export enum RiskCategoryEnum {
    Geography = 'geography',
    Identity = 'identity',
    Behavior = 'behavior',
    Transaction = 'transaction'
}


export function instanceOfRiskCategoryEnum(value: any): boolean {
    for (const key in RiskCategoryEnum) {
        if (Object.prototype.hasOwnProperty.call(RiskCategoryEnum, key)) {
            if (RiskCategoryEnum[key as keyof typeof RiskCategoryEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RiskCategoryEnumFromJSON(json: any): RiskCategoryEnum {
    return RiskCategoryEnumFromJSONTyped(json, false);
}

export function RiskCategoryEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskCategoryEnum {
    return json as RiskCategoryEnum;
}

export function RiskCategoryEnumToJSON(value?: RiskCategoryEnum | null): any {
    return value as any;
}

export function RiskCategoryEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): RiskCategoryEnum {
    return value as RiskCategoryEnum;
}

