/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * High-level business category for risk signals.
 * @export
 * @enum {string}
 */
export enum RiskCategoryEnum {
    Geography = 'geography',
    Identity = 'identity',
    Behavior = 'behavior',
    Transaction = 'transaction',
    Network = 'network'
}


export function instanceOfRiskCategoryEnum(value: any): boolean {
    for (const key in RiskCategoryEnum) {
        if (Object.prototype.hasOwnProperty.call(RiskCategoryEnum, key)) {
            if (RiskCategoryEnum[key as keyof typeof RiskCategoryEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RiskCategoryEnumFromJSON(json: any): RiskCategoryEnum {
    return RiskCategoryEnumFromJSONTyped(json, false);
}

export function RiskCategoryEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskCategoryEnum {
    return json as RiskCategoryEnum;
}

export function RiskCategoryEnumToJSON(value?: RiskCategoryEnum | null): any {
    return value as any;
}

export function RiskCategoryEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): RiskCategoryEnum {
    return value as RiskCategoryEnum;
}

