/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategorySignal } from './CategorySignal';
import {
    CategorySignalFromJSON,
    CategorySignalFromJSONTyped,
    CategorySignalToJSON,
    CategorySignalToJSONTyped,
} from './CategorySignal';

/**
 * Breakdown of risk signals by business category.
 * @export
 * @interface RiskBreakdown
 */
export interface RiskBreakdown {
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    geography?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    identity?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    behavior?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    transaction?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    network?: CategorySignal;
}

/**
 * Check if a given object implements the RiskBreakdown interface.
 */
export function instanceOfRiskBreakdown(value: object): value is RiskBreakdown {
    return true;
}

export function RiskBreakdownFromJSON(json: any): RiskBreakdown {
    return RiskBreakdownFromJSONTyped(json, false);
}

export function RiskBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'geography': json['geography'] == null ? undefined : CategorySignalFromJSON(json['geography']),
        'identity': json['identity'] == null ? undefined : CategorySignalFromJSON(json['identity']),
        'behavior': json['behavior'] == null ? undefined : CategorySignalFromJSON(json['behavior']),
        'transaction': json['transaction'] == null ? undefined : CategorySignalFromJSON(json['transaction']),
        'network': json['network'] == null ? undefined : CategorySignalFromJSON(json['network']),
    };
}

export function RiskBreakdownToJSON(json: any): RiskBreakdown {
    return RiskBreakdownToJSONTyped(json, false);
}

export function RiskBreakdownToJSONTyped(value?: RiskBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geography': CategorySignalToJSON(value['geography']),
        'identity': CategorySignalToJSON(value['identity']),
        'behavior': CategorySignalToJSON(value['behavior']),
        'transaction': CategorySignalToJSON(value['transaction']),
        'network': CategorySignalToJSON(value['network']),
    };
}

