/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The risk level of the entity.
 * @export
 * @enum {string}
 */
export enum RiskLevelEnum {
    Low = 'low',
    Medium = 'medium',
    High = 'high'
}


export function instanceOfRiskLevelEnum(value: any): boolean {
    for (const key in RiskLevelEnum) {
        if (Object.prototype.hasOwnProperty.call(RiskLevelEnum, key)) {
            if (RiskLevelEnum[key as keyof typeof RiskLevelEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RiskLevelEnumFromJSON(json: any): RiskLevelEnum {
    return RiskLevelEnumFromJSONTyped(json, false);
}

export function RiskLevelEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskLevelEnum {
    return json as RiskLevelEnum;
}

export function RiskLevelEnumToJSON(value?: RiskLevelEnum | null): any {
    return value as any;
}

export function RiskLevelEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): RiskLevelEnum {
    return value as RiskLevelEnum;
}
