/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategorySignal } from './CategorySignal';
import {
    CategorySignalFromJSON,
    CategorySignalFromJSONTyped,
    CategorySignalToJSON,
    CategorySignalToJSONTyped,
} from './CategorySignal';

/**
 * Breakdown of risk signals by business category.
 * @export
 * @interface RiskBreakdown
 */
export interface RiskBreakdown {
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    geography?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    identity?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    behavior?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    transaction?: CategorySignal;
    /**
     * 
     * @type {CategorySignal}
     * @memberof RiskBreakdown
     */
    network?: CategorySignal;
}

/**
 * Check if a given object implements the RiskBreakdown interface.
 */
export function instanceOfRiskBreakdown(value: object): value is RiskBreakdown {
    return true;
}

export function RiskBreakdownFromJSON(json: any): RiskBreakdown {
    return RiskBreakdownFromJSONTyped(json, false);
}

export function RiskBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'geography': json['geography'] == null ? undefined : CategorySignalFromJSON(json['geography']),
        'identity': json['identity'] == null ? undefined : CategorySignalFromJSON(json['identity']),
        'behavior': json['behavior'] == null ? undefined : CategorySignalFromJSON(json['behavior']),
        'transaction': json['transaction'] == null ? undefined : CategorySignalFromJSON(json['transaction']),
        'network': json['network'] == null ? undefined : CategorySignalFromJSON(json['network']),
    };
}

export function RiskBreakdownToJSON(json: any): RiskBreakdown {
    return RiskBreakdownToJSONTyped(json, false);
}

export function RiskBreakdownToJSONTyped(value?: RiskBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geography': CategorySignalToJSON(value['geography']),
        'identity': CategorySignalToJSON(value['identity']),
        'behavior': CategorySignalToJSON(value['behavior']),
        'transaction': CategorySignalToJSON(value['transaction']),
        'network': CategorySignalToJSON(value['network']),
    };
}

