/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The method used for Strong Customer Authentication (SCA).
 * @export
 * @enum {string}
 */
export enum ScaMethodEnum {
    None = 'none',
    _3dsV1 = '3ds_v1',
    _3dsV2 = '3ds_v2',
    OtpSms = 'otp_sms',
    Biometric = 'biometric',
    Fido2 = 'fido2',
    Other = 'other'
}


export function instanceOfScaMethodEnum(value: any): boolean {
    for (const key in ScaMethodEnum) {
        if (Object.prototype.hasOwnProperty.call(ScaMethodEnum, key)) {
            if (ScaMethodEnum[key as keyof typeof ScaMethodEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScaMethodEnumFromJSON(json: any): ScaMethodEnum {
    return ScaMethodEnumFromJSONTyped(json, false);
}

export function ScaMethodEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScaMethodEnum {
    return json as ScaMethodEnum;
}

export function ScaMethodEnumToJSON(value?: ScaMethodEnum | null): any {
    return value as any;
}

export function ScaMethodEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ScaMethodEnum {
    return value as ScaMethodEnum;
}

