/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreRecord } from './ScoreRecord';
import {
    ScoreRecordFromJSON,
    ScoreRecordFromJSONTyped,
    ScoreRecordToJSON,
    ScoreRecordToJSONTyped,
} from './ScoreRecord';

/**
 * List of fraud scores for a customer.
 * @export
 * @interface ScoresSuccessResponse
 */
export interface ScoresSuccessResponse {
    /**
     * Score records within the requested window.
     * @type {Array<ScoreRecord>}
     * @memberof ScoresSuccessResponse
     */
    scores?: Array<ScoreRecord>;
    /**
     * A token for retrieving the next page of results.
     * @type {string}
     * @memberof ScoresSuccessResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the ScoresSuccessResponse interface.
 */
export function instanceOfScoresSuccessResponse(value: object): value is ScoresSuccessResponse {
    return true;
}

export function ScoresSuccessResponseFromJSON(json: any): ScoresSuccessResponse {
    return ScoresSuccessResponseFromJSONTyped(json, false);
}

export function ScoresSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoresSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scores': json['scores'] == null ? undefined : ((json['scores'] as Array<any>).map(ScoreRecordFromJSON)),
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
    };
}

export function ScoresSuccessResponseToJSON(json: any): ScoresSuccessResponse {
    return ScoresSuccessResponseToJSONTyped(json, false);
}

export function ScoresSuccessResponseToJSONTyped(value?: ScoresSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scores': value['scores'] == null ? undefined : ((value['scores'] as Array<any>).map(ScoreRecordToJSON)),
        'nextPageToken': value['nextPageToken'],
    };
}

