/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoreRecord } from './ScoreRecord';
import {
    ScoreRecordFromJSON,
    ScoreRecordFromJSONTyped,
    ScoreRecordToJSON,
    ScoreRecordToJSONTyped,
} from './ScoreRecord';

/**
 * List of fraud scores for a customer.
 * @export
 * @interface ScoresSuccessResponse
 */
export interface ScoresSuccessResponse {
    /**
     * Score records within the requested window.
     * @type {Array<ScoreRecord>}
     * @memberof ScoresSuccessResponse
     */
    scores: Array<ScoreRecord>;
    /**
     * A token for retrieving the next page of results.
     * @type {string}
     * @memberof ScoresSuccessResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the ScoresSuccessResponse interface.
 */
export function instanceOfScoresSuccessResponse(value: object): value is ScoresSuccessResponse {
    if (!('scores' in value) || value['scores'] === undefined) return false;
    return true;
}

export function ScoresSuccessResponseFromJSON(json: any): ScoresSuccessResponse {
    return ScoresSuccessResponseFromJSONTyped(json, false);
}

export function ScoresSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoresSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scores': ((json['scores'] as Array<any>).map(ScoreRecordFromJSON)),
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
    };
}

export function ScoresSuccessResponseToJSON(json: any): ScoresSuccessResponse {
    return ScoresSuccessResponseToJSONTyped(json, false);
}

export function ScoresSuccessResponseToJSONTyped(value?: ScoresSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scores': ((value['scores'] as Array<any>).map(ScoreRecordToJSON)),
        'nextPageToken': value['nextPageToken'],
    };
}

