/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FraudScore } from './FraudScore';
import {
    FraudScoreFromJSON,
    FraudScoreFromJSONTyped,
    FraudScoreToJSON,
    FraudScoreToJSONTyped,
} from './FraudScore';
import type { ReasonDetail } from './ReasonDetail';
import {
    ReasonDetailFromJSON,
    ReasonDetailFromJSONTyped,
    ReasonDetailToJSON,
    ReasonDetailToJSONTyped,
} from './ReasonDetail';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';
import type { RiskBreakdown } from './RiskBreakdown';
import {
    RiskBreakdownFromJSON,
    RiskBreakdownFromJSONTyped,
    RiskBreakdownToJSON,
    RiskBreakdownToJSONTyped,
} from './RiskBreakdown';

/**
 * Fraud score for a specific transaction or entity.
 * @export
 * @interface ScoreRecord
 */
export interface ScoreRecord {
    /**
     * Universal decision identifier (for purchases, equals paymentIntentId).
     * @type {string}
     * @memberof ScoreRecord
     */
    assessmentId: string;
    /**
     * Server-minted unique payment identifier.
     * @type {string}
     * @memberof ScoreRecord
     */
    paymentIntentId?: string;
    /**
     * RFC 3339 timestamp with timezone.
     * @type {string}
     * @memberof ScoreRecord
     */
    decisionAt: string;
    /**
     * The synchronous risk decision for a purchase.
     * @type {string}
     * @memberof ScoreRecord
     */
    decision: ScoreRecordDecisionEnum;
    /**
     * DEPRECATED: Use decisionScore instead. Fraud risk score (0.00 - 1.00).
     * @type {number}
     * @memberof ScoreRecord
     */
    riskScore: number;
    /**
     * The authoritative blended risk score (0.0 - 1.0) derived from expert fusion.
     * @type {number}
     * @memberof ScoreRecord
     */
    decisionScore: number;
    /**
     * 
     * @type {FraudScore}
     * @memberof ScoreRecord
     */
    fraudScore?: FraudScore;
    /**
     * 
     * @type {RiskBreakdown}
     * @memberof ScoreRecord
     */
    breakdown?: RiskBreakdown;
    /**
     * Structured reason details for the score.
     * @type {Array<ReasonDetail>}
     * @memberof ScoreRecord
     */
    reasons?: Array<ReasonDetail>;
    /**
     * 
     * @type {EntityIds}
     * @memberof ScoreRecord
     */
    entities?: EntityIds;
    /**
     * Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.
     * 
     * @type {number}
     * @memberof ScoreRecord
     */
    amount?: number;
    /**
     * ISO 4217 currency code (e.g., 'USD').
     * @type {string}
     * @memberof ScoreRecord
     */
    currency?: string;
}

/**
* @export
* @enum {string}
*/
export enum ScoreRecordDecisionEnum {
    Approve = 'approve',
    Review = 'review',
    Decline = 'decline',
    StepUp = 'step_up'
}


/**
 * Check if a given object implements the ScoreRecord interface.
 */
export function instanceOfScoreRecord(value: object): value is ScoreRecord {
    if (!('assessmentId' in value) || value['assessmentId'] === undefined) return false;
    if (!('decisionAt' in value) || value['decisionAt'] === undefined) return false;
    if (!('decision' in value) || value['decision'] === undefined) return false;
    if (!('riskScore' in value) || value['riskScore'] === undefined) return false;
    if (!('decisionScore' in value) || value['decisionScore'] === undefined) return false;
    return true;
}

export function ScoreRecordFromJSON(json: any): ScoreRecord {
    return ScoreRecordFromJSONTyped(json, false);
}

export function ScoreRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'assessmentId': json['assessmentId'],
        'paymentIntentId': json['paymentIntentId'] == null ? undefined : json['paymentIntentId'],
        'decisionAt': json['decisionAt'],
        'decision': json['decision'],
        'riskScore': json['riskScore'],
        'decisionScore': json['decisionScore'],
        'fraudScore': json['fraudScore'] == null ? undefined : FraudScoreFromJSON(json['fraudScore']),
        'breakdown': json['breakdown'] == null ? undefined : RiskBreakdownFromJSON(json['breakdown']),
        'reasons': json['reasons'] == null ? undefined : ((json['reasons'] as Array<any>).map(ReasonDetailFromJSON)),
        'entities': json['entities'] == null ? undefined : EntityIdsFromJSON(json['entities']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
    };
}

export function ScoreRecordToJSON(json: any): ScoreRecord {
    return ScoreRecordToJSONTyped(json, false);
}

export function ScoreRecordToJSONTyped(value?: ScoreRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assessmentId': value['assessmentId'],
        'paymentIntentId': value['paymentIntentId'],
        'decisionAt': value['decisionAt'],
        'decision': value['decision'],
        'riskScore': value['riskScore'],
        'decisionScore': value['decisionScore'],
        'fraudScore': FraudScoreToJSON(value['fraudScore']),
        'breakdown': RiskBreakdownToJSON(value['breakdown']),
        'reasons': value['reasons'] == null ? undefined : ((value['reasons'] as Array<any>).map(ReasonDetailToJSON)),
        'entities': EntityIdsToJSON(value['entities']),
        'amount': value['amount'],
        'currency': value['currency'],
    };
}

