/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.9
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Interaction } from './Interaction';
import {
    InteractionFromJSON,
    InteractionFromJSONTyped,
    InteractionToJSON,
    InteractionToJSONTyped,
} from './Interaction';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';

/**
 * Interaction batch signal variant (one or more user interactions).
 * @export
 * @interface SignalsInteractionVariant
 */
export interface SignalsInteractionVariant {
    /**
     * Value for interaction signals.
     * @type {string}
     * @memberof SignalsInteractionVariant
     */
    signalType: SignalsInteractionVariantSignalTypeEnum;
    /**
     * 
     * @type {EntityIds}
     * @memberof SignalsInteractionVariant
     */
    entities: EntityIds;
    /**
     * One or more interactions associated with the signal.
     * @type {Array<Interaction>}
     * @memberof SignalsInteractionVariant
     */
    interactions: Array<Interaction>;
}

/**
* @export
* @enum {string}
*/
export enum SignalsInteractionVariantSignalTypeEnum {
    Interaction = 'interaction'
}


/**
 * Check if a given object implements the SignalsInteractionVariant interface.
 */
export function instanceOfSignalsInteractionVariant(value: object): value is SignalsInteractionVariant {
    if (!('signalType' in value) || value['signalType'] === undefined) return false;
    if (!('entities' in value) || value['entities'] === undefined) return false;
    if (!('interactions' in value) || value['interactions'] === undefined) return false;
    return true;
}

export function SignalsInteractionVariantFromJSON(json: any): SignalsInteractionVariant {
    return SignalsInteractionVariantFromJSONTyped(json, false);
}

export function SignalsInteractionVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalsInteractionVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'signalType': json['signalType'],
        'entities': EntityIdsFromJSON(json['entities']),
        'interactions': ((json['interactions'] as Array<any>).map(InteractionFromJSON)),
    };
}

export function SignalsInteractionVariantToJSON(json: any): SignalsInteractionVariant {
    return SignalsInteractionVariantToJSONTyped(json, false);
}

export function SignalsInteractionVariantToJSONTyped(value?: SignalsInteractionVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalType': value['signalType'],
        'entities': EntityIdsToJSON(value['entities']),
        'interactions': ((value['interactions'] as Array<any>).map(InteractionToJSON)),
    };
}

