/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SignalsAccountVariant } from './SignalsAccountVariant';
import {
    instanceOfSignalsAccountVariant,
    SignalsAccountVariantFromJSON,
    SignalsAccountVariantFromJSONTyped,
    SignalsAccountVariantToJSON,
} from './SignalsAccountVariant';
import type { SignalsInteractionVariant } from './SignalsInteractionVariant';
import {
    instanceOfSignalsInteractionVariant,
    SignalsInteractionVariantFromJSON,
    SignalsInteractionVariantFromJSONTyped,
    SignalsInteractionVariantToJSON,
} from './SignalsInteractionVariant';

/**
 * @type SignalsRequest
 * Request for processing application workflow signals. Determined by `signalType`.
 * 
 * @export
 */
export type SignalsRequest = { signalType: 'account' } & SignalsAccountVariant | { signalType: 'interaction' } & SignalsInteractionVariant;

export function SignalsRequestFromJSON(json: any): SignalsRequest {
    return SignalsRequestFromJSONTyped(json, false);
}

export function SignalsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalsRequest {
    if (json == null) {
        return json;
    }
    switch (json['signalType']) {
        case 'account':
            return Object.assign({}, SignalsAccountVariantFromJSONTyped(json, true), { signalType: 'account' } as const);
        case 'interaction':
            return Object.assign({}, SignalsInteractionVariantFromJSONTyped(json, true), { signalType: 'interaction' } as const);
        default:
            return json;
    }
}

export function SignalsRequestToJSON(json: any): any {
    return SignalsRequestToJSONTyped(json, false);
}

export function SignalsRequestToJSONTyped(value?: SignalsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['signalType']) {
        case 'account':
            return Object.assign({}, SignalsAccountVariantToJSON(value), { signalType: 'account' } as const);
        case 'interaction':
            return Object.assign({}, SignalsInteractionVariantToJSON(value), { signalType: 'interaction' } as const);
        default:
            return value;
    }
}

