/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
    AccountToJSONTyped,
} from './Account';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';

/**
 * Account-level signal variant (single account state snapshot).
 * @export
 * @interface SignalsAccountVariant
 */
export interface SignalsAccountVariant {
    /**
     * Value for account signals.
     * @type {string}
     * @memberof SignalsAccountVariant
     */
    signalType: SignalsAccountVariantSignalTypeEnum;
    /**
     * 
     * @type {EntityIds}
     * @memberof SignalsAccountVariant
     */
    entities: EntityIds;
    /**
     * 
     * @type {Account}
     * @memberof SignalsAccountVariant
     */
    account: Account;
}

/**
* @export
* @enum {string}
*/
export enum SignalsAccountVariantSignalTypeEnum {
    Account = 'account'
}


/**
 * Check if a given object implements the SignalsAccountVariant interface.
 */
export function instanceOfSignalsAccountVariant(value: object): value is SignalsAccountVariant {
    if (!('signalType' in value) || value['signalType'] === undefined) return false;
    if (!('entities' in value) || value['entities'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function SignalsAccountVariantFromJSON(json: any): SignalsAccountVariant {
    return SignalsAccountVariantFromJSONTyped(json, false);
}

export function SignalsAccountVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalsAccountVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'signalType': json['signalType'],
        'entities': EntityIdsFromJSON(json['entities']),
        'account': AccountFromJSON(json['account']),
    };
}

export function SignalsAccountVariantToJSON(json: any): SignalsAccountVariant {
    return SignalsAccountVariantToJSONTyped(json, false);
}

export function SignalsAccountVariantToJSONTyped(value?: SignalsAccountVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalType': value['signalType'],
        'entities': EntityIdsToJSON(value['entities']),
        'account': AccountToJSON(value['account']),
    };
}

