/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Interaction } from './Interaction';
import {
    InteractionFromJSON,
    InteractionFromJSONTyped,
    InteractionToJSON,
    InteractionToJSONTyped,
} from './Interaction';
import type { EntityIds } from './EntityIds';
import {
    EntityIdsFromJSON,
    EntityIdsFromJSONTyped,
    EntityIdsToJSON,
    EntityIdsToJSONTyped,
} from './EntityIds';

/**
 * Interaction batch signal variant (one or more user interactions).
 * @export
 * @interface SignalsInteractionVariant
 */
export interface SignalsInteractionVariant {
    /**
     * Value for interaction signals.
     * @type {string}
     * @memberof SignalsInteractionVariant
     */
    signalType: SignalsInteractionVariantSignalTypeEnum;
    /**
     * 
     * @type {EntityIds}
     * @memberof SignalsInteractionVariant
     */
    entities: EntityIds;
    /**
     * One or more interactions associated with the signal.
     * @type {Array<Interaction>}
     * @memberof SignalsInteractionVariant
     */
    interactions: Array<Interaction>;
}

/**
* @export
* @enum {string}
*/
export enum SignalsInteractionVariantSignalTypeEnum {
    Interaction = 'interaction'
}


/**
 * Check if a given object implements the SignalsInteractionVariant interface.
 */
export function instanceOfSignalsInteractionVariant(value: object): value is SignalsInteractionVariant {
    if (!('signalType' in value) || value['signalType'] === undefined) return false;
    if (!('entities' in value) || value['entities'] === undefined) return false;
    if (!('interactions' in value) || value['interactions'] === undefined) return false;
    return true;
}

export function SignalsInteractionVariantFromJSON(json: any): SignalsInteractionVariant {
    return SignalsInteractionVariantFromJSONTyped(json, false);
}

export function SignalsInteractionVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignalsInteractionVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'signalType': json['signalType'],
        'entities': EntityIdsFromJSON(json['entities']),
        'interactions': ((json['interactions'] as Array<any>).map(InteractionFromJSON)),
    };
}

export function SignalsInteractionVariantToJSON(json: any): SignalsInteractionVariant {
    return SignalsInteractionVariantToJSONTyped(json, false);
}

export function SignalsInteractionVariantToJSONTyped(value?: SignalsInteractionVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signalType': value['signalType'],
        'entities': EntityIdsToJSON(value['entities']),
        'interactions': ((value['interactions'] as Array<any>).map(InteractionToJSON)),
    };
}

