/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is a decision management and risk orchestration engine  for global commerce. It fuses adaptive machine learning, behavioral  analytics, and deterministic business rules into a high-fidelity scoring  pipeline designed for enterprise scale and auditability. Key capabilities  include real-time risk scoring, advanced behavioral fingerprinting,  geographic triangulation, and forensic decision transparency. 
 *
 * The version of the OpenAPI document: 0.2.8
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchaseSequenceEnum } from './PurchaseSequenceEnum';
import {
    PurchaseSequenceEnumFromJSON,
    PurchaseSequenceEnumFromJSONTyped,
    PurchaseSequenceEnumToJSON,
    PurchaseSequenceEnumToJSONTyped,
} from './PurchaseSequenceEnum';
import type { PurchaseInitiatorEnum } from './PurchaseInitiatorEnum';
import {
    PurchaseInitiatorEnumFromJSON,
    PurchaseInitiatorEnumFromJSONTyped,
    PurchaseInitiatorEnumToJSON,
    PurchaseInitiatorEnumToJSONTyped,
} from './PurchaseInitiatorEnum';
import type { PurchaseUsageEnum } from './PurchaseUsageEnum';
import {
    PurchaseUsageEnumFromJSON,
    PurchaseUsageEnumFromJSONTyped,
    PurchaseUsageEnumToJSON,
    PurchaseUsageEnumToJSONTyped,
} from './PurchaseUsageEnum';

/**
 * Minimal stored-credential / recurrence context.
 * @export
 * @interface StoredCredentialContext
 */
export interface StoredCredentialContext {
    /**
     * 
     * @type {PurchaseUsageEnum}
     * @memberof StoredCredentialContext
     */
    usage?: PurchaseUsageEnum;
    /**
     * 
     * @type {PurchaseSequenceEnum}
     * @memberof StoredCredentialContext
     */
    sequence?: PurchaseSequenceEnum;
    /**
     * 
     * @type {PurchaseInitiatorEnum}
     * @memberof StoredCredentialContext
     */
    initiator?: PurchaseInitiatorEnum;
}



/**
 * Check if a given object implements the StoredCredentialContext interface.
 */
export function instanceOfStoredCredentialContext(value: object): value is StoredCredentialContext {
    return true;
}

export function StoredCredentialContextFromJSON(json: any): StoredCredentialContext {
    return StoredCredentialContextFromJSONTyped(json, false);
}

export function StoredCredentialContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoredCredentialContext {
    if (json == null) {
        return json;
    }
    return {
        
        'usage': json['usage'] == null ? undefined : PurchaseUsageEnumFromJSON(json['usage']),
        'sequence': json['sequence'] == null ? undefined : PurchaseSequenceEnumFromJSON(json['sequence']),
        'initiator': json['initiator'] == null ? undefined : PurchaseInitiatorEnumFromJSON(json['initiator']),
    };
}

export function StoredCredentialContextToJSON(json: any): StoredCredentialContext {
    return StoredCredentialContextToJSONTyped(json, false);
}

export function StoredCredentialContextToJSONTyped(value?: StoredCredentialContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usage': PurchaseUsageEnumToJSON(value['usage']),
        'sequence': PurchaseSequenceEnumToJSON(value['sequence']),
        'initiator': PurchaseInitiatorEnumToJSON(value['initiator']),
    };
}

