/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PurchaseSequenceEnum } from './PurchaseSequenceEnum';
import {
    PurchaseSequenceEnumFromJSON,
    PurchaseSequenceEnumFromJSONTyped,
    PurchaseSequenceEnumToJSON,
    PurchaseSequenceEnumToJSONTyped,
} from './PurchaseSequenceEnum';
import type { PurchaseInitiatorEnum } from './PurchaseInitiatorEnum';
import {
    PurchaseInitiatorEnumFromJSON,
    PurchaseInitiatorEnumFromJSONTyped,
    PurchaseInitiatorEnumToJSON,
    PurchaseInitiatorEnumToJSONTyped,
} from './PurchaseInitiatorEnum';
import type { PurchaseUsageEnum } from './PurchaseUsageEnum';
import {
    PurchaseUsageEnumFromJSON,
    PurchaseUsageEnumFromJSONTyped,
    PurchaseUsageEnumToJSON,
    PurchaseUsageEnumToJSONTyped,
} from './PurchaseUsageEnum';

/**
 * Minimal stored-credential / recurrence context.
 * @export
 * @interface StoredCredentialContext
 */
export interface StoredCredentialContext {
    /**
     * 
     * @type {PurchaseUsageEnum}
     * @memberof StoredCredentialContext
     */
    usage?: PurchaseUsageEnum;
    /**
     * 
     * @type {PurchaseSequenceEnum}
     * @memberof StoredCredentialContext
     */
    sequence?: PurchaseSequenceEnum;
    /**
     * 
     * @type {PurchaseInitiatorEnum}
     * @memberof StoredCredentialContext
     */
    initiator?: PurchaseInitiatorEnum;
}



/**
 * Check if a given object implements the StoredCredentialContext interface.
 */
export function instanceOfStoredCredentialContext(value: object): value is StoredCredentialContext {
    return true;
}

export function StoredCredentialContextFromJSON(json: any): StoredCredentialContext {
    return StoredCredentialContextFromJSONTyped(json, false);
}

export function StoredCredentialContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoredCredentialContext {
    if (json == null) {
        return json;
    }
    return {
        
        'usage': json['usage'] == null ? undefined : PurchaseUsageEnumFromJSON(json['usage']),
        'sequence': json['sequence'] == null ? undefined : PurchaseSequenceEnumFromJSON(json['sequence']),
        'initiator': json['initiator'] == null ? undefined : PurchaseInitiatorEnumFromJSON(json['initiator']),
    };
}

export function StoredCredentialContextToJSON(json: any): StoredCredentialContext {
    return StoredCredentialContextToJSONTyped(json, false);
}

export function StoredCredentialContextToJSONTyped(value?: StoredCredentialContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usage': PurchaseUsageEnumToJSON(value['usage']),
        'sequence': PurchaseSequenceEnumToJSON(value['sequence']),
        'initiator': PurchaseInitiatorEnumToJSON(value['initiator']),
    };
}

