/* tslint:disable */
/* eslint-disable */
/**
 * Payments Risk API
 * API for detecting and scoring fraud for purchases, with lifecycle labeling and behavioral signals. v1 focuses on purchases only (`/risk/check`), with future account/session and KYC checks stubbed below. 
 *
 * The version of the OpenAPI document: 0.1.6-rc.3
 * Contact: support@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 3D Secure (3DS) data for card transactions.
 * @export
 * @interface ThreeDSData
 */
export interface ThreeDSData {
    /**
     * The version of the 3D Secure protocol used (e.g., '2.2.0').
     * @type {string}
     * @memberof ThreeDSData
     */
    version?: string;
    /**
     * Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication.
     * 
     * @type {string}
     * @memberof ThreeDSData
     */
    eci?: string;
    /**
     * The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged.
     * 
     * @type {string}
     * @memberof ThreeDSData
     */
    flow?: ThreeDSDataFlowEnum;
    /**
     * Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false).
     * 
     * @type {boolean}
     * @memberof ThreeDSData
     */
    liabilityShift?: boolean;
    /**
     * Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message.
     * 
     * @type {boolean}
     * @memberof ThreeDSData
     */
    cavvPresent?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ThreeDSDataFlowEnum {
    Frictionless = 'frictionless',
    Challenge = 'challenge'
}


/**
 * Check if a given object implements the ThreeDSData interface.
 */
export function instanceOfThreeDSData(value: object): value is ThreeDSData {
    return true;
}

export function ThreeDSDataFromJSON(json: any): ThreeDSData {
    return ThreeDSDataFromJSONTyped(json, false);
}

export function ThreeDSDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreeDSData {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'eci': json['eci'] == null ? undefined : json['eci'],
        'flow': json['flow'] == null ? undefined : json['flow'],
        'liabilityShift': json['liabilityShift'] == null ? undefined : json['liabilityShift'],
        'cavvPresent': json['cavvPresent'] == null ? undefined : json['cavvPresent'],
    };
}

export function ThreeDSDataToJSON(json: any): ThreeDSData {
    return ThreeDSDataToJSONTyped(json, false);
}

export function ThreeDSDataToJSONTyped(value?: ThreeDSData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'eci': value['eci'],
        'flow': value['flow'],
        'liabilityShift': value['liabilityShift'],
        'cavvPresent': value['cavvPresent'],
    };
}

