/* tslint:disable */
/* eslint-disable */
/**
 * Alogram PayRisk Engine
 * Alogram PayRisk is an AI-native decision engine built for the speed and  complexity of the modern commerce era. In a high-velocity world where  AI-driven threats evolve in milliseconds, Alogram provides the real-time  adaptability and forensic transparency needed to protect your ecosystem  with total confidence. We solve the challenge of balancing frictionless  growth with regulatory explainability, delivering instant, intelligent  risk orchestration at enterprise scale.  ---   ## Licensing & Terms   Our client libraries and API specifications are open-source under the **Apache License 2.0**  to ensure seamless integration into your tech stack.  Use of the Alogram PayRisk API service is proprietary and governed by our  [Terms of Service](https://alogram.ai/#tos) and your specific **Enterprise Agreement**,  if applicable.  To access the service, you must have: *   A valid Alogram API Key. *   An active subscription or signed Master Service Agreement.  Unauthorized use, including automated scraping or reverse engineering of the  scoring engine, is strictly prohibited.   ---   ## Support & Traceability   Every Alogram API response includes a unique **`x-trace-id`** header.  Please include this ID when contacting [packages@alogram.ai](mailto:packages@alogram.ai)  regarding specific transactions or errors.   ---   ## Specification   The authoritative OpenAPI specification for this version is available for download: **[Download openapi.yaml](https://developers.alogram.ai/openapi.yaml)** | **[Download openapi.json](https://developers.alogram.ai/openapi.json)** 
 *
 * The version of the OpenAPI document: 0.2.10
 * Contact: packages@alogram.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 3D Secure (3DS) data for card transactions.
 * @export
 * @interface ThreeDSData
 */
export interface ThreeDSData {
    /**
     * The version of the 3D Secure protocol used (e.g., '2.2.0').
     * @type {string}
     * @memberof ThreeDSData
     */
    version?: string;
    /**
     * Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication.
     * 
     * @type {string}
     * @memberof ThreeDSData
     */
    eci?: string;
    /**
     * The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged.
     * 
     * @type {string}
     * @memberof ThreeDSData
     */
    flow?: ThreeDSDataFlowEnum;
    /**
     * Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false).
     * 
     * @type {boolean}
     * @memberof ThreeDSData
     */
    liabilityShift?: boolean;
    /**
     * Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message.
     * 
     * @type {boolean}
     * @memberof ThreeDSData
     */
    cavvPresent?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ThreeDSDataFlowEnum {
    Frictionless = 'frictionless',
    Challenge = 'challenge'
}


/**
 * Check if a given object implements the ThreeDSData interface.
 */
export function instanceOfThreeDSData(value: object): value is ThreeDSData {
    return true;
}

export function ThreeDSDataFromJSON(json: any): ThreeDSData {
    return ThreeDSDataFromJSONTyped(json, false);
}

export function ThreeDSDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreeDSData {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'eci': json['eci'] == null ? undefined : json['eci'],
        'flow': json['flow'] == null ? undefined : json['flow'],
        'liabilityShift': json['liabilityShift'] == null ? undefined : json['liabilityShift'],
        'cavvPresent': json['cavvPresent'] == null ? undefined : json['cavvPresent'],
    };
}

export function ThreeDSDataToJSON(json: any): ThreeDSData {
    return ThreeDSDataToJSONTyped(json, false);
}

export function ThreeDSDataToJSONTyped(value?: ThreeDSData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'eci': value['eci'],
        'flow': value['flow'],
        'liabilityShift': value['liabilityShift'],
        'cavvPresent': value['cavvPresent'],
    };
}

